### PR TITLE
Fix context to native sync for sentry context types

### LINKED ISSUE #3006: Contexts.fromJson fails with type error with SentryFirebaseRemoteConfigIntegration enabled
### Platform

Flutter Mobile Android

### Obfuscation

Disabled

### Debug Info

Disabled

### Doctor

```sh
$ flutter doctor -v
[✓] Flutter (Channel stable, 3.32.1, on macOS 15.5 24F74 darwin-arm64, locale en-US)
    [306ms]
    • Flutter version 3.32.1 on channel stable at /<REDACTED>/fvm/versions/3.32.1
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b25305a883 (4 weeks ago), 2025-05-29 10:40:06 -0700
    • Engine revision 1425e5e9ec
    • Dart version 3.8.1
    • DevTools version 2.45.1

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0-rc4)
    [900ms]
    • Android SDK at /<REDACTED>/Library/Android/sdk
    • Platform android-35, build-tools 35.0.0-rc4
    • Java binary at:
      /<REDACTED>/Library/Java/JavaVirtualMachines/jbr-17.0.14/Contents/Home/bin/java
      This JDK is specified in your Flutter configuration.
      To change the current JDK, run: `flutter config --jdk-dir="path/to/jdk"`.
    • Java version OpenJDK Runtime Environment JBR-17.0.14+1-1367.22-nomod (build
      17.0.14+1-b1367.22)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.4) [619ms]
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16F6
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web [67ms]
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.3) [67ms]
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.6+-13368085-b895.109)

[✓] IntelliJ IDEA Ultimate Edition (version 2025.1.3) [66ms]
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 86.0.2
    • Dart plugin version 251.26927.39

[✓] VS Code (version 1.98.2) [9ms]
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

⢿^[[[✓] Connected device (1 available) [5.6s]
    • sdk gphone64 arm64 (mobile)      • emulator-5554             • android-arm64  •
      Android 16 (API 36) (emulator)

[✓] Network resources [175ms]
    • All expected network resources are available.

• No issues found!
```

### Version

9.1.0

### Steps to Reproduce

1. Init `SentryFlutter` with `SentryFirebaseRemoteConfigIntegration`:
```dart
await SentryFlutter.init((options) {
    options
      ...
      ..addIntegration(
        SentryFirebaseRemoteConfigIntegration(
          firebaseRemoteConfig: FirebaseRemoteConfig.instance,
        ),
      );
    ...
  }, appRunner: appRunner);
```
2. Run the Flutter app on an Android device

### Expected Result

There are no console errors

### Actual Result

Console error is produced:
```sh
type 'String' is not a subtype of type 'Map<dynamic, dynamic>'
         #0      new Contexts.fromJson (package:sentry/src/protocol/contexts.dart:74:54)
         #1      _LoadContextsIntegrationEventProcessor.apply (package:sentry_flutter/src/integrations/load_contexts_integration.dart:62:35)
         <asynchronous suspension>
         #2      runEventProcessors (package:sentry/src/event_processor/run_event_processors.dart:26:52)
         <asynchronous suspension>
         #3      SentryClient.captureTransaction (package:sentry/src/sentry_client.dart:405:27)
         <asynchronous suspension>
         #4      Hub.captureTransaction (package:sentry/src/hub.dart:595:22)
         <asynchronous suspension>
         #5      SentryTracer.finish (package:sentry/src/sentry_tracer.dart:160:7)
         <asynchronous suspension>
```

The value of `data[SentryFeatureFlags.type]`:
https://github.com/getsentry/sentry-dart/blob/e788bd4a93003174ff6134df5ac6dd50c3d8e09a/dart/lib/src/protocol/contexts.dart#L73

is `Instance of 'SentryFeatureFlags'`, but it should be a `Map`

### Are you willing to submit a PR?

None

### PR DESCRIPTION
**Pull request by denrase**
## :scroll: Description

Fixes an issue where we'd call toString() on sentry context types when synging to native. This in turn broke load contexts integration, as a map was expected, and instead it was the toString() string.

## :bulb: Motivation and Context

Fixes #3006 

## :green_heart: How did you test it?

Unit tests. Ran on sample app.

## :pencil: Checklist

- [x] I reviewed submitted code
- [x] I added tests to verify changes
- [ ] No new PII added or SDK only sends newly added PII if `sendDefaultPii` is enabled
- [ ] I updated the docs if needed
- [x] All tests passing
- [x] No breaking changes

### CODE REVIEW

File: flutter/lib/src/native/native_scope_observer.dart [hunk 1]
```diff
@@ -5,13 +5,27 @@ import 'package:sentry/sentry.dart';
...
+      } catch (_) {
+        _options.log(
+          SentryLevel.error,
+          "Failed to set context '$key' with value '$value'.",
+        );
+      }
+    } else {
+      await _native.setContexts(key, value);
+    }
   }
```
Comment (buenaflor) [inline flutter/lib/src/native/native_scope_observer.dart:29]: shouldn't we instead just make sure that values passed in are serializable? e.g adding asserts here and then fix it in the respective method that calls setContexts?

Comment (denrase) [reply flutter/lib/src/native/native_scope_observer.dart:29]: The this method is defined to take `dynamic` values. So while this special observer needs to pass serialised values over the native bridge, others might not, that's why it's only implemented here.

While i'm not sure that this is API that is used much by users, we do export it in `sentry.dart` and observers can be added in options.

**Review by buenaflor — APPROVED** [review]
lgtm 👍
