### PR TITLE
Fix: Do not throw when Throwable type is not supported for associating errors to a transaction

### LINKED ISSUE #680: Error in console when calling Sentry.captureException
_Platform:_
- [x]  Dart
- [ ]  Flutter Android or iOS
- [ ]  Flutter Web

_IDE:_
- [ ]  VSCode
- [x]  IntelliJ/AS
- [ ]  XCode
- [ ]  Other, which one?

_split-debug-info and obfuscate (Flutter Android or iOS) or CanvasKit (Flutter Web):_
- [ ]  Enabled
- [x]  Disabled

_Platform installed with:_
- [x] pub.dev
- [ ] GitHub

Output of the command `flutter doctor -v` below:

The output goes here...

The version of the SDK (See pubspec.lock):
**6.1.2**

---
I have the following issue:

Invalid argument (Expandos are not allowed on strings, numbers, booleans or null): "My custom error message: error message"
         #0      Expando._checkType (dart:core-patch/expando_patch.dart:144:7)
         #1      Expando.[] (dart:core-patch/expando_patch.dart:20:5)
         #2      _WeakMap.get (package:sentry/src/hub.dart:518:20)
         #3      Hub._assignTraceContext (package:sentry/src/hub.dart:475:37)
         #4      Hub.captureException (package:sentry/src/hub.dart:138:19)
         #5      Sentry.captureException (package:sentry/src/sentry.dart:159:12)
         #6      captureSentryException (package:utils/helper_functions.dart:119:10)
         #7      logError (package:utils/helper_functions.dart:109:5)
         #8      ProdFeedRepo.getFeedPosts.<anonymous closure>.<anonymous closure> (package:data/prod_feed_repo.dart:158:11)
         #9      _rootRunUnary (dart:async/zone.dart:1362:47)
         #10     _CustomZone.runUnary (dart:async/zone.dart:1265:19)
         #11     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1170:7)
         #12     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
         #13     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
         #14     _SyncBroadcastStreamController._sendData (dart:async/broadcast_stream_controller.dart:378:25)
         #15     _BroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:244:5)
         #16     _StartWithStreamSink.add (package:rxdart/src/transformers/start_with.dart:15:10)
         #17     forwardStream.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:rxdart/src/utils/forwarding_stream.dart:31:49)
         #18     forwardStream.runCatching (package:rxdart/src/utils/forwarding_stream.dart:21:12)
         #19     forwardStream.<anonymous closure>.<anonymous closure> (package:rxdart/src/utils/forwarding_stream.dart:31:28)
         #20     _rootRunUnary (dart:async/zone.dart:1362:47)
         #21     _CustomZone.runUnary (dart:async/zone.dart:1265:19)
         #22     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1170:7)
         #23     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
         #24     _DelayedData.perform (dart:async/stream_impl.dart:591:14)
         #25     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:706:11)
         #26     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:663:7)
         #27     _rootRun (dart:async/zone.dart:1346:47)
         #28     _CustomZone.run (dart:async/zone.dart:1258:19)
         #29     _CustomZone.runGuarded (dart:async/zone.dart:1162:7)
         #30     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1202:23)
         #31     _rootRun (dart:async/zone.dart:1354:13)
         #32     _CustomZone.run (dart:async/zone.dart:1258:19)
         #33     _CustomZone.runGuarded (dart:async/zone.dart:1162:7)
         #34     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1202:23)
         #35     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
         #36     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)

**Steps to reproduce:**
- Call Sentry.captureException() with the error message passed into required params.

**Actual result:**
- Actual

**Expected result:**
- Result

### PR DESCRIPTION
**Pull request by marandaneto**
## :scroll: Description
Fix: Do not throw when Throwable type is not supported for associating errors to a transaction

## :bulb: Motivation and Context
Fixes https://github.com/getsentry/sentry-dart/issues/680

## :pencil: Checklist

- [X] I reviewed submitted code
- [X] I added tests to verify changes
- [ ] I updated the docs if needed
- [X] All tests passing
- [X] No breaking changes

### CODE REVIEW

File: dart/lib/src/hub.dart [hunk 1]
```diff
@@ -510,20 +511,45 @@ class _StackItem {
...
+      return;
+    }
+    try {
+      if (_expando[throwable] == null) {
+        _expando[throwable] = MapEntry(span, transaction);
+      }
+    } catch (exception, stackTrace) {
+      _options.logger(
+        SentryLevel.info,
+        'Throwable type: ${throwable.runtimeType} is not supported for associating errors to a transaction.',
```
Comment (ueman) [inline dart/lib/src/hub.dart:533]: Maybe this should point to the [docs](https://api.dart.dev/stable/2.15.1/dart-core/Expando-class.html), which says which types are not supported? Or maybe include the list of unspported types?

File: dart/lib/src/hub.dart [hunk 2]
```diff
@@ -31,7 +31,7 @@ class Hub {
 
   late SentryTracesSampler _tracesSampler;
 
-  final _WeakMap _throwableToSpan = _WeakMap();
+  late final _WeakMap _throwableToSpan;
```
Comment (ueman) [inline dart/lib/src/hub.dart:34]: Also FYI: Starting with Dart 2.17 there's a [WeakReference](https://github.com/dart-lang/sdk/blob/main/CHANGELOG.md).

Comment (marandaneto) [reply dart/lib/src/hub.dart:34]: will take some time, thanks for pointing out o/

File: dart/lib/src/hub.dart (hunk 1 above)
Comment (marandaneto) [reply dart/lib/src/hub.dart:533]: `throwable.runtimeType` does the job for now, but indeed a better logging message here would be awesome, I will merge and release for now because it's a bug and later improve it.

**Review by brustolin — APPROVED** [review]
LGTM
