### PR TITLE
Log errors captured in integrations with SentryLogger

### LINKED ISSUE #640: Consider making Dart stack trace available in events
I want to log some events to console in the `beforeSend` callback (for example from the `runZonedGuarded` integration) but the original `StackTrace` is not available and I can't find a good way to log the `SentryStackTrace`.

Does this make sense?

### PR DESCRIPTION
**Pull request by kuhnroyal**
This is just a very quick PR for discussion.

## :scroll: Description
* add logger name parameter
* log errors from Zone, Isolate and Flutter integrations

## :bulb: Motivation and Context
Fixes https://github.com/getsentry/sentry-dart/issues/640

## :pencil: Checklist

- [x] I reviewed submitted code
- [ ] I added tests to verify changes
- [ ] I updated the docs if needed
- [ ] All tests passing
- [ ] No breaking changes

### CODE REVIEW

File: dart/lib/src/isolate_error_integration.dart [hunk 1]
```diff
@@ -52,6 +52,14 @@ Future<void> handleIsolateError(
     final dynamic throwable = error.first;
     final dynamic stackTrace = error.last;
 
+    options.logger(
+      SentryLevel.error,
+      'Uncaught isolate error',
+      logger: 'sentry.isolateError',
+      exception: throwable,
+      stackTrace: StackTrace.fromString(stackTrace),
```
Comment (marandaneto) [inline dart/lib/src/isolate_error_integration.dart]: can this throw? if `stackTrace` is null or it cant be a `StackTrace`, or any other reason? otherwise we need to wrap up in a try catch, maybe this is an instance of `StackTrace` already

Comment (kuhnroyal) [reply dart/lib/src/isolate_error_integration.dart]: Yea this needs to be checked for null but IIRC this is a String because it has to be sent across isolates.

Comment (marandaneto) [reply dart/lib/src/isolate_error_integration.dart]: yep, I'd then check all the cases, if it's null, if it's a StackTrace already, and do the `StackTrace.fromString` last case, also worth checking if `fromString` does not throw with an invalid string that is not a stack trace.

Comment (kuhnroyal) [reply dart/lib/src/isolate_error_integration.dart]: From the isolate error handler doc:
>   /// The second element is a `String` representation of an accompanying
  /// stack trace, or `null` if no stack trace was provided.
  /// To convert this back to a [StackTrace] object, use [StackTrace.fromString].

**Comment by kuhnroyal** [comment]
The sentry_flutter builds seem to be failing because they don't use the correct dart dependency.

File: dart/lib/src/isolate_error_integration.dart [hunk 2]
```diff
@@ -31,7 +31,7 @@ class IsolateErrorIntegration extends Integration {
 
 RawReceivePort _createPort(Hub hub, SentryOptions options) {
   return RawReceivePort(
-    (dynamic error) async {
+    (Object? error) async {
```
Comment (marandaneto) [inline dart/lib/src/isolate_error_integration.dart]: I'd rather rollback those changes because of https://github.com/getsentry/sentry-dart/issues/511
so ideally we'd do it all together and go thru pre-releases to avoid errors

Comment (kuhnroyal) [reply dart/lib/src/isolate_error_integration.dart]: I reverted all the dynamic changes except for the list types.

**Comment by marandaneto** [comment]
@kuhnroyal CI fails ->

> ERROR: ../lib/src/default_integrations.dart:77:11: Error: No named parameter with the name 'logger'.
> ERROR:           logger: 'sentry.flutterError',

File: flutter/example/pubspec.yaml [hunk 3]
```diff
@@ -11,15 +11,21 @@ environment:
 dependencies:
   flutter:
     sdk: flutter
+  sentry:
   sentry_flutter:
```
Comment (marandaneto) [inline flutter/example/pubspec.yaml:15]: instead of removing the relative path, I'd rather add for `sentry` too, I recall having issues when using `dependency_overrides` and using `pana`, so we keep the same as every other example too.

Comment (kuhnroyal) [reply flutter/example/pubspec.yaml:15]: That doesn't work because `sentry_flutter` pulls `sentry: ^x.x.x` - that results in a dependency conflict if it is specified as path dependency. It needs to be an override.

Also pana ist not really relevant for an app since it is not being published to `pub.dev` or am I missing something ?

Comment (marandaneto) [reply flutter/example/pubspec.yaml:15]: yeah, I didnt run the dependency conflict before so its fine.

**Comment by marandaneto** [comment]
@kuhnroyal add changelog entry and its good to go, thanks for doing this
