### PR TITLE
fix(sentry-dart): remove transitive dart:io reference for web

### LINKED ISSUE #1893: Can't compile example_web - sentry_io dependency leaked back somehow?
### Platform

Dart Web

### Obfuscation

Disabled

### Debug Info

Disabled

### Doctor

<details><summary>Dart version</summary>
<p>

```
Dart SDK version: 3.3.0 (stable) (Tue Feb 13 10:25:19 2024 +0000) on "linux_x64"
```

</p>
</details> 

### Version

7.16.1

### Steps to Reproduce

```
git clone https://github.com/getsentry/sentry-dart
git switch 7.16.1
cd sentry-dart/example_web
dart pub upgrade
dart run build_runner serve web
```

### Expected Result

Example to compile successfully with DDC and serve `main.dart.js` file

### Actual Result

```
[WARNING] build_web_compilers:entrypoint on web/main.dart:
Skipping compiling sentry_dart_web_example|web/main.dart with ddc because some of its
transitive libraries have sdk dependencies that not supported on this platform:

sentry|lib/src/sentry_isolate_extension.dart
sentry|lib/src/sentry_isolate.dart
sentry|lib/src/sentry_attachment/io_sentry_attachment.dart

https://github.com/dart-lang/build/blob/master/docs/faq.md#how-can-i-resolve-skipped-compiling-warnings
```

### Are you willing to submit a PR?

Yes

### Extra info:

This might be related: https://github.com/getsentry/sentry-dart/issues/1369
However, this issue has been fixed by https://github.com/getsentry/sentry-dart/pull/1371/files

So I'm a bit confused as following the dependency chain shows that I should NOT import `_io` version of anything. :confused:

### PR DESCRIPTION
**Pull request by daniel-v**
TransportUtils imported sentry_io.dart which prevented web projects such as example_web from building when build_runner was used.

Resolves getsentry/sentry-dart#1893

## :scroll: Description

Removed `sentry_io.dart` dependency in a file that is used by web projects too.

## :bulb: Motivation and Context

Running `dart run build_runner build` or `serve` in `example_web` folder failed because of `sentry_io.dart` was imported in `transport_utils.dart`.

More broadly, `sentry_io.dart` in `transport_utils.dart` file prevents any dart web project from compiling that uses `build_web_compilers` (webdev).

## :green_heart: How did you test it?

Locally built `example_web` with the following command:

```sh
dart run build_runner build
```

Observed failure before changeset and success after.

## :pencil: Checklist

- [x] I reviewed submitted code
- [x] I added tests to verify changes
- [ ] No new PII added or SDK only sends newly added PII if `sendDefaultPii` is enabled
- [x] I updated the docs if needed
- [ ] All tests passing
- [x] No breaking changes

### CODE REVIEW

**Comment by daniel-v** [comment]
This is my first PR to you guys, any feedback on the process is much appreciated!

**Comment by buenaflor** [comment]
@daniel-v thanks daniel for the contribution 🙏 do you know if we can set up some (meaningful) tests so this doesn't happen in the future?

note: some ci is currently broken so expect some of it to be red

**Comment by daniel-v** [comment]
@buenaflor I've updated CHANGELOG.md to satisfy the CI (DANGER).

As for the tests go, currently there are 3 ways I can image.

1. Do not run `dart run test -p "chrome"` but instead run `dart run build_runner test -r -- -p "chrome"`. This will catch these kinds of errors, however test times will be _significantly_ higher. On the plus side, this is the closest to how `package:sentry` will be used on web; I don't think `dart2js` is much used these days.
2. Write a GH action step where `example_web` is compiled - this should provide feedback on CI but not locally. I see this as the least effort. 
3. Write a test with `@TestOn('vm')` where we invoke tooling which compiles `example_web` project and examine the return code of the process. This approach should probably take least amount of time and provide feedback locally.

CI is important, I'm only comfortable with No 3. Options 1 and 2 would be stuff I approach my CI guru in my team with.

**Comment by buenaflor** [comment]
@daniel-v do you think we can do 3. in this pr ? I'm on board as long as it's consistent and quick to set up now

**Review by stefanosiano — APPROVED** [review]
thanks for this! 🙏

**Comment by daniel-v** [comment]
Sure, I'll throw in a test, @buenaflor

File: dart/test/example_web_compile_test.dart [hunk 1]
```diff
@@ -0,0 +1,74 @@
...
+///
+/// Returns [_CommandResult] with exitCode and stdout as a single sting
+Future<_CommandResult> _runProcess(String command,
+    {String workingDirectory = '.'}) async {
+  final parts = command.split(' ');
+  assert(parts.isNotEmpty);
+  final cmd = parts[0];
+  final args = parts.skip(1).toList();
+  final process =
+      await Process.start(cmd, args, workingDirectory: workingDirectory);
```
Comment (daniel-v) [inline dart/test/example_web_compile_test.dart:56]: Picked `Process.start()` over eg. `Process.runSync()` so that stdout and stderr can be forwarded while the tests are running for immediate feedback to the dev.

File: dart/test/example_web_compile_test.dart [hunk 2]
```diff
@@ -0,0 +1,74 @@
...
+          'dart run build_runner build -r web -o build --delete-conflicting-outputs',
+          workingDirectory: _exampleWebWorkingDir);
+      expect(result.exitCode, 0,
+          reason: 'Could not compile example_web project');
+      expect(
+          result.stdout,
+          isNot(contains(
+              'Skipping compiling sentry_dart_web_example|web/main.dart')),
+          reason:
+              'Could not compile main.dart, likely because of dart:io import.');
```
Comment (daniel-v) [inline dart/test/example_web_compile_test.dart]: Checking exitCode is not sufficient - build_runner returns with exit code 0 and a WARNING that main.dart could not be compiled if `dart:io` was detected. Testing against this warning message is necessary.

**Comment by daniel-v** [comment]
@stefanosiano @buenaflor I've added some tests. On my local machine, they run in <20s. On GH actions, it might take longer. The default test timeout is 30 seconds. I hope it won't be necessary to increase it. 

I couldn't run the tests on a _Windows_ machine. I was trying to pay attention to working with platform agnostic mechanisms to determine the path of `example_web`. That being said, I'd be happy if a test run on a windows machine could be arranged (I don't have access to one).

Other than that, I consider this feature complete.

**Comment by buenaflor** [comment]
@daniel-v the tests are currently failing, in some of our runners. it's a bit inconvenient since you cannot run the workflow files as an outside contributor but you can always ping me @ discord and I can run it for you asap when you debug it

**Comment by daniel-v** [comment]
Updated the tests because they were transiently failing on linux and almost always on windows.

There were 3 problems:

1. Computing `exmample_web` path was "too smart" - simplified it (error: `The directory name is invalid.`)
2. `Bad state: StreamSink is already bound to a stream` was fixed by using `.listen` instead of await for when working with process' stdout.
3. Test are being ran out of order with random seed. This was taken into account and the 2 tests were merged into 1 to ensure proper order of external commands being executed.

**Comment by buenaflor** [comment]
thx for the contribution @daniel-v! 🙌
