### PR TITLE
Fix samples

### LINKED ISSUE #367: Rename User in Sentry example
_Platform:_
- [ ]  Dart
- [x]  Flutter Android or iOS
- [ ]  Flutter Web

_IDE:_
- [x]  VSCode
- [ ]  IntelliJ/AS
- [ ]  XCode
- [ ]  Other, which one?

_split-debug-info and obfuscate (Flutter Android or iOS) or CanvasKit (Flutter Web):_
- [ ]  Enabled
- [ ]  Disabled

_Platform installed with:_
- [x] pub.dev
- [ ] GitHub

Output of the command `flutter doctor -v` below:
[√] Flutter (Channel stable, 2.0.1, on Microsoft Windows [Version 10.0.14393], locale pl-PL)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[√] Android Studio (version 4.1.0)
[√] VS Code (version 1.54.3)
[√] Connected device (1 available)

The output goes here...

The version of the SDK (See pubspec.lock):
```
sdks:
  dart: ">=2.12.0 <3.0.0"
  flutter: ">=1.24.0-7.0"
```

---
I have the following issue:
After upgrading some packages in my app as well as Sentry and Sentry_Flutter (  sentry: ^4.0.6, sentry_flutter: ^4.0.6) the User is not recognized as a function or class "The function 'User' isn't defined. Try importing the library that defines 'User', correcting the name to the name of an existing function, or defining a function named 'User'."
In this file I have both : `import 'package:sentry/sentry.dart'; import 'package:sentry_flutter/sentry_flutter.dart';`

The code I am using it in is:
```
import 'package:sentry/sentry.dart';
import 'package:sentry_flutter/sentry_flutter.dart';

import '../services/device_info.dart';
import '../services/shared_data.dart';

Future<void> initializeSentryUserInfo() async {
  await getDeviceDetails();

  Sentry.configureScope((scope) {
    scope
      ..user = User(
        id: SharedData().userEmail,
        email: SharedData().userEmail,
        extras: <String, dynamic>{
          'email': SharedData().userEmail,
          'platform': SharedData().platform,
          'androidVersion': SharedData().androidVersion,
          'appVersion': SharedData().appVersion,
          'deviceName': SharedData().deviceName,
          'deviceVersion': SharedData().deviceVersion,
        },
      );
  });
}
```

**Expected result:**
- Result 
Being able to set up user properties for reporting ... 

Thanks!

### PR DESCRIPTION
**Pull request by marandaneto**
## :scroll: Description
Fix samples
_#skip-changelog_

## :bulb: Motivation and Context
Fix #367
Added also uncaught exception to the web example

## :green_heart: How did you test it?
running and checking events

## :pencil: Checklist

- [X] I reviewed submitted code
- [ ] I added tests to verify changes
- [ ] I updated the docs if needed
- [X] All tests passing
- [X] No breaking changes

### CODE REVIEW

File: dart/example/event_example.dart [hunk 1]
```diff
@@ -5,15 +5,15 @@ final event = SentryEvent(
...
   extra: const <String, String>{'section': '1'},
-  fingerprint: const <String>['example-dart'],
-  user: User(
+  // fingerprint: const <String>['example-dart'],
+  user: SentryUser(
     id: '800',
     username: 'first-user',
     email: 'first@user.lan',
-    ipAddress: '127.0.0.1',
+    // ipAddress: '127.0.0.1',
```
Comment (marandaneto) [inline dart/example/event_example.dart]: I enabled sendDefaultPii

File: dart/example/event_example.dart [hunk 2]
```diff
@@ -5,15 +5,15 @@ final event = SentryEvent(
   serverName: 'server.dart',
   release: '1.4.0-preview.1',
   environment: 'Test',
-  message: Message('This is an example Dart event.'),
+  message: SentryMessage('This is an example Dart event.'),
   tags: const <String, String>{'project-id': '7371'},
   extra: const <String, String>{'section': '1'},
-  fingerprint: const <String>['example-dart'],
-  user: User(
+  // fingerprint: const <String>['example-dart'],
```
Comment (marandaneto) [inline dart/example/event_example.dart]: its nice to test and see how events are grouped by default and not forcing a `fingerprint`

File: dart/example/main.dart [hunk 3]
```diff
@@ -84,9 +86,10 @@ Future<void> runApp() async {
     );
 
     print('Capture exception result : SentryId : $sentryId');
-  } finally {
-    Sentry.close();
   }
+
+  // capture unhandled error
+  await loadConfig();
```
Comment (marandaneto) [inline dart/example/main.dart:92]: no need to Sentry.close, unhandled exception already `await` so process die only after

File: dart/example_web/web/main.dart [hunk 4]
```diff
@@ -73,15 +78,13 @@ Future<void> captureMessage() async {
   if (sentryId != SentryId.empty()) {
     querySelector('#messageResult')?.style.display = 'block';
   }
-  Sentry.close();
```
Comment (marandaneto) [inline dart/example_web/web/main.dart:76]: its a web page, no need to call close either

File: dart/example/event_example.dart (hunk 1 above)
Comment (ueman) [reply dart/example/event_example.dart]: I think it would make sense to write this as a comment in the example.

File: dart/example/event_example.dart (hunk 2 above)
Comment (ueman) [reply dart/example/event_example.dart]: Same here.

**Comment by ueman** [comment]
The example should probably be at least compiled in CI to make sure it works.

**Comment by marandaneto** [comment]
> The example should probably be at least compiled in CI to make sure it works.

its been always compiled, I guess we've changed something that broke it, I'll create an issue for that.
#374

File: dart/example/event_example.dart (hunk 1 above)
Comment (marandaneto) [inline dart/example/event_example.dart]:
```suggestion
    // ipAddress: '127.0.0.1', sendDefaultPii feature is enabled
```

File: dart/example/event_example.dart (hunk 2 above)
Comment (marandaneto) [inline dart/example/event_example.dart]:
```suggestion
  // fingerprint: const <String>['example-dart'], fingerprint forces events to group together
```

File: dart/example/main.dart [hunk 5]
```diff
@@ -38,23 +44,19 @@ Future<void> main() async {
...
+      ..user = SentryUser(
         id: '800',
         username: 'first-user',
         email: 'first@user.lan',
-        ipAddress: '127.0.0.1',
+        // ipAddress: '127.0.0.1',
         extras: <String, String>{'first-sign-in': '2020-01-01'},
       )
-      ..fingerprint = ['example-dart']
+      // ..fingerprint = ['example-dart']
```
Comment (marandaneto) [inline dart/example/main.dart]:
```suggestion
      // ..fingerprint = ['example-dart'], fingerprint forces events to group together
```

File: dart/example/main.dart [hunk 6]
```diff
@@ -38,23 +44,19 @@ Future<void> main() async {
 
   Sentry.configureScope((scope) {
     scope
-      ..user = User(
+      ..user = SentryUser(
         id: '800',
         username: 'first-user',
         email: 'first@user.lan',
-        ipAddress: '127.0.0.1',
+        // ipAddress: '127.0.0.1',
```
Comment (marandaneto) [inline dart/example/main.dart]:
```suggestion
        // ipAddress: '127.0.0.1', sendDefaultPii feature is enabled
```

**Review by ueman — APPROVED** [review]
