### PR TITLE
Setup `dart doc --dry-run` and fix warnings

### LINKED ISSUE #1396: Add `dartdoc_options` and set warnings as errors
### Description

```
dartdoc:
  errors:
    - unresolved-doc-reference
```

We'd like to know the docs issues before releasing/during development.
It'd be awesome if there's an option similar to `--fatal-infos`, so warnings are treated as errors.
https://github.com/dart-lang/dartdoc

Of course, fixing all pending issues as well.

### PR DESCRIPTION
**Pull request by denrase**
#skip-changelog

## :scroll: Description

- Setup `dart doc --dry-run`
- Treat wrong link warnings as error
- Fix wrong link warnings

## :bulb: Motivation and Context

Closes #1396

## :pencil: Checklist

- [x] I reviewed submitted code
- [ ] I added tests to verify changes
- [ ] No new PII added or SDK only sends newly added PII if `sendDefaultPii` is enabled
- [ ] I updated the docs if needed
- [ ] All tests passing
- [x] No breaking changes

### CODE REVIEW

File: dart/lib/src/protocol/sentry_package.dart [hunk 1]
```diff
@@ -1,9 +1,9 @@
 import 'package:meta/meta.dart';
 
-/// A [SentryPackage] part of the [Sdk].
+/// A [SentryPackage] part of the sdk.
```
Comment (marandaneto) [inline dart/lib/src/protocol/sentry_package.dart]: Maybe SDK would be better since its an acronym.

File: dart/lib/src/protocol/sentry_stack_frame.dart [hunk 2]
```diff
@@ -37,12 +37,12 @@ class SentryStackFrame {
 
   final List<String>? _preContext;
 
-  /// An immutable list of source code lines before context_line (in order) – usually [lineno - 5:lineno].
+  /// An immutable list of source code lines before context_line (in order) – usually `[lineno - 5:lineno]`.
```
Comment (marandaneto) [inline dart/lib/src/protocol/sentry_stack_frame.dart]: Maybe we avoid `[]` instead since its reserved? its strange to add `[]` within the code snippets.

File: dio/dartdoc_options.yaml [hunk 3]
```diff
@@ -0,0 +1,3 @@
+dartdoc:
```
Comment (marandaneto) [inline dio/dartdoc_options.yaml]: What if we do a symlink to the dart folder for all packages? they are all the same.

File: sqflite/lib/src/sentry_batch.dart [hunk 4]
```diff
@@ -68,6 +68,7 @@ class SentryBatch implements Batch {
     });
   }
 
+  /// @nodoc
```
Comment (marandaneto) [inline sqflite/lib/src/sentry_batch.dart]: does it exist something similar to https://github.com/getsentry/sentry-javascript/blob/8482c0a02960d191d369db7af712ec48b9033f44/packages/core/src/hub.ts#L96 ?

Comment (denrase) [reply sqflite/lib/src/sentry_batch.dart]: The issue is that theres a warning in the inherited doc, thats why i disabled it for this method.

Comment (marandaneto) [reply sqflite/lib/src/sentry_batch.dart]: And that is from `Batch` that we don't have control over? add a comment then.

**Review by marandaneto — APPROVED** [review]

**Comment by denrase** [comment]
@marandaneto Looks like the issue is using `DioError`, which was deprecated a couple of hours ago: https://pub.dev/packages/dio/changelog

We should probably tackle this in a sep. issue?

Bildschirmfoto 2023-06-06 um 16 59 21

**Comment by marandaneto** [comment]
> @marandaneto Looks like the issue is using `DioError`, which was deprecated a couple of hours ago: [pub.dev/packages/dio/changelog](https://pub.dev/packages/dio/changelog)
> 
> We should probably tackle this in a sep. issue?
> 
> Bildschirmfoto 2023-06-06 um 16 59 21

@denrase I see, so we have to add `// ignore: deprecated_member_use` to keep compatibility for a while.
Would you like to do it in a separate PR?
