### PR TITLE
Fix: Use PlatformDispatcher.onError in Flutter 3.3

### LINKED ISSUE #988: Use PlatformDispatcher.onError instead of custom zone starting with Flutter 3.3
_Platform:_
- [ ]  Dart
- [x]  Flutter Android or iOS
- [x]  Flutter Web

Starting with Flutter 3.3, apps should now use PlatformDispatcher.onError instead of running the app in a custom zone to catch errors. I believe sentry_flutter is using a custom zone to catch errors.

Release notes: https://medium.com/flutter/whats-new-in-flutter-3-3-893c7b9af1ff#:~:text=In%20this%20release%2C%20instead%20of%20using%20a%20custom%20Zone%2C%20you%20should%20catch%20all%20errors%20and%20exceptions%20by%20setting%20the%20PlatformDispatcher.onError%20callback.
The error handling page was also updated to reflect these changes: https://docs.flutter.dev/testing/errors

### PR DESCRIPTION
**Pull request by denrase**
## :scroll: Description

Closes #988

## :green_heart: How did you test it?

Added unit tests. Some expectations that were run in a closure would always evaluate as passed. Moved those out fo we don't have false positives anymore.

## :pencil: Checklist

- [x] I reviewed submitted code
- [x] I added tests to verify changes
- [ ] I updated the docs if needed
- [x] All tests passing
- [x] No breaking changes

## :crystal_ball: Next steps

Should we update the documentation to reflect the change?

### CODE REVIEW

**Comment by marandaneto** [comment]
@denrase based on what I understood from https://github.com/getsentry/sentry-dart/issues/988
We'd do a try catch with `NoSuchMethodError` in order to detect if `PlatformDispatcher.onError` is available and use it automatically instead of having a boolean flag that has to be specified to the user, didn't work?

**Comment by marandaneto** [comment]
> @denrase based on what I understood from #988 We'd do a try catch with `NoSuchMethodError` in order to detect if `PlatformDispatcher.onError` is available and use it automatically instead of having a boolean flag that has to be specified to the user, didn't work?

nvm, the method `isOnErrorSupported` was already builtin.

File: dart/lib/src/sentry.dart [hunk 1]
```diff
@@ -36,6 +36,7 @@ class Sentry {
   static Future<void> init(
     OptionsConfiguration optionsConfiguration, {
     AppRunner? appRunner,
+    bool callAppRunnerInRunZonedGuarded = true,
```
Comment (marandaneto) [inline dart/lib/src/sentry.dart:39]: If we detect the new callback automatically, why would we need that?

Comment (marandaneto) [inline dart/lib/src/sentry.dart]: I'd mark this as `@internal` since users should not touch this anyway.

File: flutter/lib/src/sentry_flutter.dart [hunk 2]
```diff
@@ -45,27 +44,26 @@ mixin SentryFlutter {
     final native = SentryNative();
     native.setNativeChannel(nativeChannel);
 
+    final wrapper = PlatformDispatcherWrapper(PlatformDispatcher.instance);
```
Comment (ueman) [inline flutter/lib/src/sentry_flutter.dart]: The PlatformDispatcher should be accessed via one of the WidgetsBindings:

> Consider avoiding static references to this singleton through [PlatformDispatcher.instance](https://api.flutter.dev/flutter/dart-ui/PlatformDispatcher/instance.html) and instead prefer using a binding for dependency resolution such as WidgetsBinding.instance.platformDispatcher. See [PlatformDispatcher.instance](https://api.flutter.dev/flutter/dart-ui/PlatformDispatcher/instance.html) for more information about why this is preferred.

https://api.flutter.dev/flutter/dart-ui/PlatformDispatcher-class.html

Comment (marandaneto) [reply flutter/lib/src/sentry_flutter.dart]: You can use the `BindingUtils.getWidgetsBindingInstance().platformDispatcher`.

File: flutter/lib/src/sentry_flutter.dart [hunk 3]
```diff
@@ -45,27 +44,26 @@ mixin SentryFlutter {
...
+    final isOnErrorSupported = wrapper.isOnErrorSupported(flutterOptions);
```
Comment (marandaneto) [inline flutter/lib/src/sentry_flutter.dart:49]: Since the check is already being done here, we don't need to check the availability again inside the `OnErrorIntegration` class.

File: flutter/lib/src/sentry_flutter.dart (hunk 2 above)
Comment (denrase) [reply flutter/lib/src/sentry_flutter.dart:47]: Is it ok to access the widgets binding instance at this place?

Comment (marandaneto) [reply flutter/lib/src/sentry_flutter.dart]: It could be that this only works after `WidgetsFlutterBinding.ensureInitialized()` which is executed likely after? has to be tested.

Comment (ueman) [reply flutter/lib/src/sentry_flutter.dart]: `WidgetsFlutterBinding.ensureInitialized()` should be basically the first thing the SDK does. 

When running with a zone, it has to be called in the zone, but to check whether to use the zone it has to be called before. That's an interesting challenge.

Comment (denrase) [reply flutter/lib/src/sentry_flutter.dart]: Ok, then we probably can't use it through `WidgetsFlutterBinding.ensureInitialized()`, as we cannot tell automatically before this call wether we should use the zone or not. 🤔

Comment (ueman) [reply flutter/lib/src/sentry_flutter.dart]: Maybe the solution to do it automatically is then to use `PlatformDispatcher.instance` despite it being discouraged since it doesn't require the WidgetsBinding to be initialized :|

Sorry for the trouble 😅

Comment (denrase) [reply flutter/lib/src/sentry_flutter.dart]: @marandaneto WDYT? Change back to `PlatformDispatcher.instance`?

Comment (marandaneto) [reply flutter/lib/src/sentry_flutter.dart]: @denrase did you test this? https://github.com/getsentry/sentry-dart/pull/1039#discussion_r985701810
It was a hunch and a question, maybe it works?

Comment (marandaneto) [reply flutter/lib/src/sentry_flutter.dart]: The docs says:

> The only place that WidgetsBinding.instance.platformDispatcher is inappropriate is if access to these APIs is required before the binding is initialized by invoking runApp() or WidgetsFlutterBinding.instance.ensureInitialized(). In that case, it is necessary (though unfortunate) to use the [PlatformDispatcher.instance](https://api.flutter.dev/flutter/dart-ui/PlatformDispatcher/instance.html) object statically.

So in this case, it'd be fine to use `PlatformDispatcher.instance`, in case it's necessary.

File: CHANGELOG.md [hunk 4]
```diff
@@ -1,5 +1,11 @@
 # Changelog
 
+## Unreleased
+
+### Fixes
```
Comment (marandaneto) [inline CHANGELOG.md]: Maybe Features since its a new thing?

File: flutter/lib/src/sentry_flutter.dart (hunk 2 above)
Comment (denrase) [reply flutter/lib/src/sentry_flutter.dart]: Tested this and we indeed have a null value for `BindingUtils.getWidgetsBindingInstance()`. The approach with `PlatformDispatcher.instance works`:

Bildschirmfoto 2022-10-10 um 11 07 24

Bildschirmfoto 2022-10-10 um 11 08 03

File: flutter/lib/src/sentry_flutter.dart [hunk 5]
```diff
@@ -45,27 +45,27 @@ mixin SentryFlutter {
     final native = SentryNative();
     native.setNativeChannel(nativeChannel);
 
+    final platformDispatcher = PlatformDispatcher.instance;
+    final wrapper = PlatformDispatcherWrapper(platformDispatcher);
+    bool isOnErrorSupported = wrapper.isOnErrorSupported(flutterOptions);
```
Comment (marandaneto) [inline flutter/lib/src/sentry_flutter.dart]:
```suggestion
    final isOnErrorSupported = wrapper.isOnErrorSupported(flutterOptions);
```

File: flutter/test/mocks.mocks.dart [hunk 6]
```diff
@@ -1,11 +1,10 @@
-// Mocks generated by Mockito 5.3.1 from annotations
+// Mocks generated by Mockito 5.2.0 from annotations
```
Comment (marandaneto) [inline flutter/test/mocks.mocks.dart]: If this is needed, upgrade your local mockito version and run it again, otherwise, just revert these changes.

**Comment by marandaneto** [comment]
@denrase there are lint issues:

> info • Unused import: 'binding_utils.dart' • lib/src/sentry_flutter.dart:9:8 • unused_import
>    info • The member 'callAppRunnerInRunZonedGuarded' can only be used within its package • lib/src/sentry_flutter.dart:68:9 • invalid_use_of_internal_member

File: CHANGELOG.md [hunk 7]
```diff
@@ -10,6 +10,10 @@
 
 ## 6.12.0
 
+### Features
+
+- Use PlatformDispatcher.onError in Flutter 3.3 ([#1039](https://github.com/getsentry/sentry-dart/pull/1039))
```
Comment (marandaneto) [inline CHANGELOG.md]: Move to unreleased section

**Comment by denrase** [comment]
@marandaneto Can't reproduce the lint error error below locally, do you have a guess?

Bildschirmfoto 2022-10-11 um 14 07 00

**Comment by marandaneto** [comment]
> @marandaneto Can't reproduce the lint error error below locally, do you have a guess?
> 
> Bildschirmfoto 2022-10-11 um 14 07 00

That's not a problem, something we already discussed before:
https://github.com/dart-lang/pana/issues/1020

**Review by marandaneto — APPROVED** [review]
Thanks a lot @denrase

**Comment by marandaneto** [comment]
@denrase there's a bug here, `OnErrorIntegration` isn't executing correctly because the `binding` is null and it returns.
Test out if errors are being captured correctly with the new (onError) and old integration (zonedGuard).

**Review by marandaneto — CHANGES_REQUESTED** [review]
Left a comment
https://github.com/getsentry/sentry-dart/pull/1039#issuecomment-1274662566

**Comment by marandaneto** [comment]
@denrase 

> Should we update the documentation to reflect the change?

Let's amend the docs that `runZonedGuarded` is run when `PlatformDispatcher.onError` isn't available.

The same for the README files, examples, etc within the repo for Flutter.

File: flutter/lib/src/sentry_flutter.dart [hunk 8]
```diff
@@ -45,27 +44,28 @@ mixin SentryFlutter {
...
-      options: flutterOptions,
-    );
+    await Sentry.init((options) async {
+      await optionsConfiguration(options as SentryFlutterOptions);
+    },
+        appRunner: appRunner,
+        // ignore: invalid_use_of_internal_member
+        options: flutterOptions,
+        // ignore: invalid_use_of_internal_member
+        callAppRunnerInRunZonedGuarded: !isOnErrorSupported);
```
Comment (ueman) [inline flutter/lib/src/sentry_flutter.dart]: If you add a trailing comma here, it doesn't have a diff this big

**Review by marandaneto — APPROVED** [review]
