### PR TITLE
fix(sqflite): recursion in `openDatabase` when using `SentrySqfliteDatabaseFactory`

### LINKED ISSUE #3229: Infinite recursion when _databaseFactory is null in SentrySqfliteDatabaseFactory (line 53)
### Platform

Dart, Flutter Mobile Android

### Obfuscation

Disabled

### Debug Info

Disabled

### Doctor

N/A (not an environment problem)

### Version

9.6.0

### Steps to Reproduce

1. Following the [official tutorial](https://docs.sentry.io/platforms/dart/guides/flutter/integrations/sqflite-instrumentation/), I set up sqflite databaseFactory like this: `databaseFactory = SentrySqfliteDatabaseFactory();` (without passing an argument to its inner databaseFactory property, which does prevent the issue as a workaround)
2. When I then run either openDatabase() or openDatabaseWithSentry(), the openDatabase method in **SentrySqfliteDatabaseFactory** is called (in file *sentry_sqflite_database_factory.dart*)
3. At line 53, this code happens: `final databaseFactory = _databaseFactory ?? this;` and since _databaseFactory is null, that local databaseFactory instance receives *this*
4. That causes unintended recursion at line 57, since the method now calls itself

### Expected Result

If *_databaseFactory* is null (when **SentrySqfliteDatabaseFactory**'s *databaseFactory* isn't set) , `openDatabase()` should fallback to the global default sqflite databaseFactory, not itself. There should be no risk of recursion or stack overflow.

### Actual Result

When tracing is disabled and _databaseFactory is null, calling openDatabase may result in infinite recursion or a stack overflow, as the factory calls itself repeatedly.

### Are you willing to submit a PR?

Yes

### PR DESCRIPTION
**Pull request by buenaflor**
## :scroll: Description

Fixes a recursion happening when calling `openDatabase` on a `SentrySqfliteDatabaseFactory` instance where no database factory has been passed

## :bulb: Motivation and Context

Fixes #3229 

## :green_heart: How did you test it?
Unit tests

Also ran the test without the fix which fails as expected

## :pencil: Checklist

- [x] I reviewed submitted code
- [x] I added tests to verify changes
- [ ] No new PII added or SDK only sends newly added PII if `sendDefaultPii` is enabled
- [ ] I updated the docs if needed
- [x] All tests passing
- [x] No breaking changes

### CODE REVIEW

File: packages/sqflite/lib/src/sentry_sqflite_database_factory.dart [hunk 1]
```diff
@@ -1,6 +1,7 @@
 import 'package:meta/meta.dart';
 import 'package:sentry/sentry.dart';
 import 'package:sqflite/sqflite.dart';
+import 'package:sqflite/sqflite.dart' as sqflite show databaseFactory;
```
Comment (denrase) [inline packages/sqflite/lib/src/sentry_sqflite_database_factory.dart]: Import is now "duplicated"

```Dart
import 'package:sqflite/sqflite.dart';
import 'package:sqflite/sqflite.dart' as sqflite show databaseFactory;
```

Could we just use the latter with the `sqflite` prefix?

**Review by denrase — APPROVED** [review]
LGTM with one suggestion.

File: packages/sqflite/lib/src/sentry_sqflite_database_factory.dart (hunk 1 above)
Comment (buenaflor) [reply packages/sqflite/lib/src/sentry_sqflite_database_factory.dart]: I can change it so all sqflite calls in this file use the sqflite prefix, yea
