### PR TITLE
fix: onError should be `handled: false` by default

### LINKED ISSUE #2898: `onError` should by default be unhandled
Currently we report errors caught by the `PlatformDispatcher` in `onError` as handled by default. <br><br>However the default should be false since we are catching an unhandled error.

Currently: 

```dart
final handled = _defaultOnError?.call(exception, stackTrace) ?? true;
```

Expected:

```dart
final handled = _defaultOnError?.call(exception, stackTrace) ?? false;
```

Note:

* This might change grouping (I'm not sure), so we have to be careful here
* Fixing this means we also don't prevent Flutter from printing the err -> from Flutter doc `This callback must return true if it has handled the error. Otherwise, it must return false and a fallback mechanism such as printing to stderr will be used`

### PR DESCRIPTION
**Pull request by buenaflor**
## :bulb: Motivation and Context

Closes #2898 

Note:
 - I checked and this does not affect grouping
 - This will however affect crash free rate but we're still including this in a new major so we have to call this out properly

## :pencil: Checklist

- [ ] I reviewed submitted code
- [ ] I added tests to verify changes
- [ ] No new PII added or SDK only sends newly added PII if `sendDefaultPii` is enabled
- [ ] I updated the docs if needed
- [ ] All tests passing
- [ ] No breaking changes

### CODE REVIEW

**Comment by buenaflor** [comment]
@ueman since you added this integration back then do you have any concerns with this change?

File: flutter/lib/src/integrations/on_error_integration.dart [hunk 1]
```diff
@@ -41,15 +39,7 @@ class OnErrorIntegration implements Integration<SentryFlutterOptions> {
     _defaultOnError = wrapper.onError;
 
     _integrationOnError = (Object exception, StackTrace stackTrace) {
-      _options!.logger(
-        SentryLevel.error,
-        "Uncaught Platform Error",
-        logger: 'sentry.platformError',
-        exception: exception,
-        stackTrace: stackTrace,
-      );
```
Comment (buenaflor) [inline flutter/lib/src/integrations/on_error_integration.dart:50]: maybe we should keep the logging if it was handled, otherwise we might swallow the error?

Comment (denrase) [reply flutter/lib/src/integrations/on_error_integration.dart:50]: Sounds reasonable to me. AS I understood, users will only get logging info if the method returns false, right?

**Review by denrase — APPROVED** [review]
LGTM 👍

File: flutter/lib/src/integrations/on_error_integration.dart (hunk 1 above)
Comment (buenaflor) [reply flutter/lib/src/integrations/on_error_integration.dart:50]: yup exactly

from flutter api docs:

This callback must return true if it has handled the error. Otherwise, it must return false and a fallback mechanism such as printing to stderr will be used
