### PR TITLE
v9: Parent-child relationship for the PlatformExceptions and Cause

### LINKED ISSUE #1859: [v9] Parent-child relationship for the PlatformExceptions and Cause
### Description

The Dart/Flutter SDK currently supports [`PlatformExceptions`](https://github.com/getsentry/sentry-dart/blob/681136bc4576771f144f52c7209c03ce3ace88bb/flutter/lib/src/event_processor/platform_exception_event_processor.dart#L5) and [`ExceptionCause`](https://github.com/getsentry/sentry-dart/blob/681136bc4576771f144f52c7209c03ce3ace88bb/dart/lib/src/exception_cause_extractor.dart#L32).

### Related links

- https://github.com/getsentry/sentry-dart/blob/681136bc4576771f144f52c7209c03ce3ace88bb/flutter/lib/src/event_processor/platform_exception_event_processor.dart#L5
- https://github.com/getsentry/sentry-dart/blob/681136bc4576771f144f52c7209c03ce3ace88bb/dart/lib/src/exception_cause_extractor.dart#L32
- Sentry RFC https://github.com/getsentry/rfcs/blob/main/text/0079-exception-groups.md#example-event
- Example JS impl https://github.com/getsentry/sentry-javascript/pull/8463

### Notes

- ~I'm not aware of how used or not the AggregateErrors are. After a quick search doesn't seem too common.~ 
- Implementing this might likely change grouping so it should be done in a major version. 
- Dart could add the parent-child relationship to the linked errors as described in the RFC.

```[tasklist]
### Related
- [ ] https://github.com/getsentry/sentry/issues/64088
- [ ] https://github.com/getsentry/sentry-java/pull/3184
``` 

```[tasklist]
### Tasks
- [x] Implement parent-child relationship for `PlatformException`
- [x] Implement parent-child relationship for `ExceptionCause`
```

### Example `PlatformException` chaining

Image

### PR DESCRIPTION
**Pull request by denrase**
## :scroll: Description

- Introduce child relationships (exceptions) in SentryExceptions, so we can preserve nested relationships.
- Flatten exceptions into list with ids and parent references according to RFC.

## :bulb: Motivation and Context

Closes  #1859

## :pencil: Checklist

- [x] I reviewed submitted code
- [x] I added tests to verify changes
- [ ] No new PII added or SDK only sends newly added PII if `sendDefaultPii` is enabled
- [ ] I updated the docs if needed
- [ ] All tests passing
- [ ] No breaking changes

### CODE REVIEW

File: dart/lib/src/event_processor/exception/exception_group_event_processor.dart [hunk 1]
```diff
@@ -0,0 +1,23 @@
...
+    if (sentryExceptions.isEmpty) {
+      return event;
+    }
+    final firstException = sentryExceptions.first;
+
+    if (sentryExceptions.length > 1 || firstException.exceptions == null) {
+      // If already a list or no child exceptions, no grouping possible/needed.
+      return event;
+    } else {
+      final grouped = firstException.flatten().reversed.toList(growable: false);
```
Comment (denrase) [inline dart/lib/src/event_processor/exception/exception_group_event_processor.dart]: We might not need to reverse the order, as the references to the parent should be enough. Then we can also revert the test expectations in the client tests.

File: dart/lib/src/protocol/sentry_exception.dart [hunk 2]
```diff
@@ -92,4 +93,51 @@ class SentryException {
...
+  }
+
+  @internal
+  void addException(SentryException exception) {
+    _exceptions ??= [];
+    _exceptions!.add(exception);
+  }
+
+  @internal
+  List<SentryException> flatten({int? parentId, int id = 0}) {
```
Comment (denrase) [inline dart/lib/src/protocol/sentry_exception.dart]: We could consider moving this to `ExceptionGroupEventProcessor`, as it's business logic and only used there.

Comment (buenaflor) [reply dart/lib/src/protocol/sentry_exception.dart]: sure we can do that

File: dart/lib/src/sentry.dart [hunk 3]
```diff
@@ -110,6 +111,9 @@ class Sentry {
     options.addEventProcessor(DeduplicationEventProcessor(options));
 
     options.prependExceptionTypeIdentifier(DartExceptionTypeIdentifier());
+
+    // Added last to ensure all error events have correct parent/child relationships
+    options.addEventProcessor(ExceptionGroupEventProcessor());
```
Comment (buenaflor) [inline dart/lib/src/sentry.dart:119]: might be an edge case but I guess it's also possible that the custom user added event processor will be added after this right?

File: dart/lib/src/event_processor/exception/exception_group_event_processor.dart (hunk 1 above)
Comment (buenaflor) [reply dart/lib/src/event_processor/exception/exception_group_event_processor.dart]: did you test whether the UI changes if we don't reverse it?

**Review by buenaflor — COMMENTED** [review]
looks good! only got couple questionos

File: dart/lib/src/sentry.dart (hunk 3 above)
Comment (denrase) [reply dart/lib/src/sentry.dart:119]: Yeah, question is if users are using said event processor to group multiple exceptions. In that case, the fallback would send them as before. Don't think we can do much, as users would have to put the errors in the tree structure.

**Comment by buenaflor** [comment]
Couple of merge conflicts are here, prolly because of the mutable data PR

**Comment by denrase** [comment]
@buenaflor So i tested on Android emulator. While both exceptions are shown, the order is reversed. Which would suggest that the relationships build here are ignored, no? The json has the references in the mechanism, so this should all be correct. Is this feature activated on sentry.io?

https://sentry-sdks.sentry.io/issues/6182166435/events/latest/?project=5428562&query=is%3Aunresolved%20issue.priority%3A%5Bhigh%2C%20medium%5D&referrer=latest-event&stream_index=0

Bildschirmfoto 2025-04-07 um 14 08 28

Bildschirmfoto 2025-04-07 um 14 10 06

**Comment by buenaflor** [comment]
@denrase not sure how the order is supposed to be

but regarding the UI, it should look like this (or used to)

image

I triggered the platform exception with the implementation of this PR https://github.com/getsentry/sentry-dart/pull/1998

Not sure if they removed this UI change

**Comment by buenaflor** [comment]
~From the docs: https://develop.sentry.dev/sdk/data-model/event-payloads/exception/
`Multiple values represent chained exceptions and should be sorted oldest to newest` so I believe the second picture is correct? runtime exception -> platformexception~

@denrase there's also a couple dartt analyzer warnings

**Comment by denrase** [comment]
@buenaflor So the first picture is according to the RFC, where the root is the last in the list.

**Comment by buenaflor** [comment]
as discussed let's check the mentioned PR if we added something wrong to make the UI look like in my comment

**Comment by denrase** [comment]
```json
"exception":
{
    "values":
    [
        {
            "type": "PlatformException",
            "value": "PlatformException(error, Catch this platform exception!, null, java.lang.RuntimeException: Catch this platform exception!\n\tat io.sentry.samples.flutter.MainActivity$configureFlutterEngine$1.onMethodCall(MainActivity.kt:38)\n\tat io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:267)\n\tat io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:292)\n\tat io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)\n\tat io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)\n\tat android.os.Handler.handleCallback(Handler.java:942)\n\tat android.os.Handler.dispatchMessage(Handler.java:99)\n\tat android.os.Looper.loopOnce(Looper.java:201)\n\tat android.os.Looper.loop(Looper.java:288)\n\tat android.app.ActivityThread.main(ActivityThread.java:7924)\n\tat java.lang.reflect.Method.invoke(Native Method)\n\tat com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)\n\tat com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)\n)",
            "mechanism":
            {
                "type": "chained",
                "exception_id": 1,
                "parent_id": 0,
            }
        },
        {
            "type": "RuntimeException",
            "value": "Catch this platform exception!",
            "mechanism":
            {
                "type": "sentry-flutter",
                "is_exception_group": true,
                "exception_id": 0
            }
        }
    ]
},
```

Above is what we get from the PR of @ueman. We have a PlatformExcetion, which contains an exception that occured in Android. We parse this either from `details` or `stackTrace`:

``` dart
PlatformException(
  details: null,
  stackTrace: RuntimeException(...)
)
```

The `RuntimeException` is the innermost, so in this example it is the root and last in order.

```dart
PlatformException(id: 1, parent: 0), RuntimeException(id: 0, parent: null),
```

What does not make sense to me is `is_exception_group: true` in this example, as there are not multiple children on the same level. But only if we set this value, we have the UI which shows hierarchy.

Bildschirmfoto 2025-04-09 um 14 23 21

In tests we have the case where both `details` and `stackTrace`:

``` dart
PlatformException(
  details: SomeException(...),
  stackTrace: RuntimeException(...)
)
```

I'm not sure that this is a case that occures, but since we have a test case for it, I'm assuming that we need to handle it.

But what would in this case the structure look like? Initially, I have implemented it the other way around, where `PlatformException` is the root and also a group, as it contains two children on the same level:

```dart
RuntimeException(id: 2, parent: 0), SomeException(id: 1, parent: 0), PlatformException(id: 0, parent: null),
```

But seeing the other PR, I don't think that is correct.

So in summary:

- ~~I think the PR of @ueman is correct where the innermost exception is the root.~~ Actually I'm not sure anymore, just did an error with `PlatformException` as root, but sentry took the innermost `RuntimeExcetion` for the title: https://sentry-sdks.sentry.io/issues/5141932961/events/latest/?project=5428562&query=is%3Aunresolved%20issue.priority%3A%5Bhigh%2C%20medium%5D&referrer=latest-event&stream_index=0
- But if so, i don't know how to build the hierarchy with both `details` and `stackTrace` populated with an error.

**Comment by buenaflor** [comment]
based on JS and Python impl the root / parent should be marked with `is_exception_group: true`, in this case the `PlatformException`

File: dart/lib/src/protocol/sentry_exception.dart [hunk 4]
```diff
@@ -86,10 +88,25 @@ class SentryException {
         type: type ?? this.type,
         value: value ?? this.value,
         module: module ?? this.module,
-        stackTrace: stackTrace ?? this.stackTrace,
-        mechanism: mechanism ?? this.mechanism,
+        stackTrace: stackTrace ?? this.stackTrace?.copyWith(),
+        mechanism: mechanism ?? this.mechanism?.copyWith(),
```
Comment (buenaflor) [inline dart/lib/src/protocol/sentry_exception.dart:92]: do we need the copyWith?

File: dart/lib/src/sentry_exception_factory.dart [hunk 5]
```diff
@@ -22,6 +22,7 @@ class SentryExceptionFactory {
   }) {
     var throwable = exception;
     Mechanism? mechanism;
+
```
Comment (buenaflor) [inline dart/lib/src/sentry_exception_factory.dart]:
```suggestion
```

**Review by buenaflor — APPROVED** [review]
Got 1 last question but lgtm 👍

File: dart/lib/src/protocol/sentry_exception.dart (hunk 4 above)
Comment (denrase) [reply dart/lib/src/protocol/sentry_exception.dart:92]: For the tests, yeah. There we use copy with and without this, we'd just share the same instance of stackTrace/mecahnism between multiple tests, now that it's immutable.

Comment (buenaflor) [reply dart/lib/src/protocol/sentry_exception.dart:92]: is it possible to fix this? since copyWith is deprecated we will remove it at some point

but if it's too much work it's fine, we can do it when we eventually remove it

**Comment by ueman** [comment]
> But if so, i don't know how to build the hierarchy with both details and stackTrace populated with an error.

FWIW, that's not a case I've ever seen in production. It's either in details or in stackTrace, but not both. I would suggest to not handle the case where both contain an exception and wait until someone complains and then care about it.

File: dart/lib/src/protocol/sentry_exception.dart (hunk 4 above)
Comment (buenaflor) [reply dart/lib/src/protocol/sentry_exception.dart:92]: Let's leave it for now and handle this some other time
