### PR TITLE
Fix: Breadcrumbs "Concurrent Modification"

### LINKED ISSUE #941: "Concurrent modification" on ListQueue<Breadcrumb> in 6.6.3
_Platform:_
- [ ]  Dart
- [X]  Flutter Android or iOS
- [ ]  Flutter Web

_IDE:_
- [ ]  VSCode
- [X]  IntelliJ/AS
- [ ]  XCode
- [ ]  Other, which one?

_split-debug-info and obfuscate (Flutter Android or iOS) or CanvasKit (Flutter Web):_
- [ ]  Enabled
- [X]  Disabled

_Platform installed with:_
- [X] pub.dev
- [ ] GitHub

Output of the command `flutter doctor -v` below:

```
[✓] Flutter (Channel stable, 3.0.4, on macOS 12.4 21F79 darwin-x64, locale pl-PL)
    • Flutter version 3.0.4 at /Users/tomasznoinski/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 85684f9300 (11 days ago), 2022-06-30 13:22:47 -0700
    • Engine revision 6ba2af10bb
    • Dart version 2.17.5
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tomasznoinski/Library/Android/sdk/
    • Platform android-31, build-tools 30.0.2
    • ANDROID_SDK_ROOT = /Users/tomasznoinski/Library/Android/sdk/
    • Java binary at: /Library/Java/JavaVirtualMachines/temurin-8.jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (Temurin)(build 1.8.0_332-b09)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] IntelliJ IDEA Community Edition (version 2022.1.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 69.0.4
    • Dart plugin version 221.5921.27

[✓] VS Code (version 1.61.2)
    • VS Code at /Users/tomasznoinski/Downloads/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] VS Code (version 1.61.2)
    • VS Code at /Users/tomasznoinski/Downloads/Visual Studio Code 2.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • Pixel 4a (mobile) • 192.168.123.32:5555 • android-arm64  • Android 12 (API 32)
    • macOS (desktop)   • macos               • darwin-x64     • macOS 12.4 21F79 darwin-x64
    • Chrome (web)      • chrome              • web-javascript • Google Chrome 103.0.5060.114

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

The version of the SDK (See pubspec.lock):
**6.6.3**

---
I have the following issue:

When I upgrade from 6.6.1 to 6.6.3 my app starts throwing the following exception while attempting to report exceptions to Sentry:
```
I/flutter (20758): #1      ListQueue._checkModification (dart:collection/queue.dart:864:7)
I/flutter (20758): #2      _ListQueueIterator.moveNext (dart:collection/queue.dart:971:12)
I/flutter (20758): #3      Scope.clone (package:sentry/src/scope.dart:401:30)
I/flutter (20758): #4      _CustomZone.registerBinaryCallback (dart:async/zone.dart:1364:19)
I/flutter (20758): #5      _asyncErrorWrapperHelper (dart:async-patch/async_patch.dart:64:8)
I/flutter (20758): #6      Sentry.captureMessage (package:sentry/src/sentry.dart:170:12)
(...)
```

This is my code calling captureMessage directly (i.e. frame #7):
```
    Sentry.captureMessage(
      message,
      withScope: (scope) {
        scope.setContexts(_scopeContextKey, data);

        if (fingerprint != null) {
          scope.fingerprint = [fingerprint];
        }
      },
      level: level.toSentryLevel(),
    );
```

To be clear: this is NOT happening in 6.6.1, that version works fine.

**Steps to reproduce:**

I don't know how hard it is to reproduce, my app is closed source; but I didn't try hard to trigger the bug, it's there every time.

### PR DESCRIPTION
**Pull request by denrase**
## :scroll: Description

Closes #941

## :green_heart: How did you test it?

Ran unit tests.

## :pencil: Checklist

- [x] I reviewed submitted code
- [ ] I added tests to verify changes
- [ ] I updated the docs if needed
- [ ] All tests passing
- [x] No breaking changes

### CODE REVIEW

File: dart/lib/src/scope.dart [hunk 1]
```diff
@@ -398,17 +398,17 @@ class Scope {
...
+    for (final breadcrumb in List.from(_breadcrumbs)) {
       await clone.addBreadcrumb(breadcrumb);
     }
 
     for (final eventProcessor in _eventProcessors) {
       clone.addEventProcessor(eventProcessor);
     }
 
-    contexts.forEach((key, value) {
+    contexts.forEach((key, value) async {
```
Comment (ueman) [inline dart/lib/src/scope.dart]: Shouldn't this also follow the same pattern as above to prevent a concurrent modification?

Comment (denrase) [reply dart/lib/src/scope.dart]: Good question, opted to specifically fix the reported issue.

File: dart/lib/src/scope.dart [hunk 2]
```diff
@@ -390,29 +390,29 @@ class Scope {
...
       clone.addEventProcessor(eventProcessor);
     }
 
-    contexts.forEach((key, value) {
+    Map.from(contexts).forEach((key, value) async {
       if (value != null) {
-        clone.setContexts(key, value);
+        await clone.setContexts(key, value);
       }
     });
```
Comment (marandaneto) [inline dart/lib/src/scope.dart]: @denrase that has to be a sync call, so the solution should rather be:

```
for (final entry in contexts.entries) {
      if (entry.value != null) {
        await clone.setContexts(entry.key, entry.value);
      }
    }
```

Otherwise each item of the loop is async but we don't await to its future.

**Review by marandaneto — APPROVED** [review]
