### PR TITLE
Fix: captureMessage defaults SentryLevel to info

### LINKED ISSUE #305: `captureMessage` defaults to level `error`.
I'm using `sentry.dart` 4.0.5 on a server app. I tried a `captureMessage` but the `level comes up as `error`:

`Sentry.captureMessage('test from pub client with crumbs');`

As a result the last crumb, which becomes the message itself, also has level `error`:

image

[Sample on sentry.io](https://sentry.io/organizations/bruno-garcia/issues/2229790948/?project=1857674&query=is%3Aunresolved)

Also, note `was active: false`. Is this the correct behavior?

### PR DESCRIPTION
**Pull request by marandaneto**
## :scroll: Description
Fix: captureMessage defaults SentryLevel to info

## :bulb: Motivation and Context
Fix #305

## :pencil: Checklist

- [X] I reviewed submitted code
- [X] I added tests to verify changes
- [ ] I updated the docs if needed
- [X] All tests passing
- [X] No breaking changes

### CODE REVIEW

File: dart/test/sentry_client_test.dart [hunk 1]
```diff
@@ -122,6 +122,19 @@ void main() {
       expect(capturedEvent.stackTrace is SentryStackTrace, true);
     });
 
+    test('capture message defaults to info level', () async {
```
Comment (ueman) [inline dart/test/sentry_client_test.dart:124]: Does it make sense to create a test like this for the static Sentry methods, too? To make sure that it gets passed down correctly. Or does a test like that already exist?

Comment (marandaneto) [reply dart/test/sentry_client_test.dart:124]: `should capture message` test on SentryClient pass `SentryLevel.error` and asserts it, but yeah one coming from the Sentry static class makes sense, will do it, thanks

**Review by ueman — APPROVED** [review]
