### PR TITLE
Fix print recursion detection

### LINKED ISSUE #2581: Recursion during print() call.Abort adding print() call as Breadcrumb.
### Platform

Flutter Web

### Obfuscation

Enabled

### Debug Info

Enabled

### Doctor

```
[!] Flutter (Channel [user-branch], 3.24.5, on macOS 15.1 24B83 darwin-arm64, locale en-VN)
    ! Flutter version 3.24.5 on channel [user-branch] at /Users/truonglemanh/flutter
      Currently on an unknown channel. Run `flutter channel` to switch to an official channel.
      If that doesn't fix the issue, reinstall Flutter by following instructions at https://flutter.dev/setup.
    ! Upstream repository unknown source is not a standard remote.
      Set environment variable "FLUTTER_GIT_URL" to unknown source to dismiss this error.
    • Framework revision dec2ee5c1f (9 weeks ago), 2024-11-13 11:13:06 -0800
    • Engine revision a18df97ca5
    • Dart version 3.5.4
    • DevTools version 2.37.3
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and
      upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/truonglemanh/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16B40
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.96.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.102.0

[✓] Connected device (3 available)
    • macOS (desktop)                 • macos                 • darwin-arm64   • macOS 15.1 24B83 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad • darwin         • macOS 15.1 24B83 darwin-arm64
    • Chrome (web)                    • chrome                • web-javascript • Google Chrome 132.0.6834.84
    ! Error: Browsing on the local area network for it’s iPad. Ensure the device is unlocked and attached with a cable or associated with the same
      local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources
    • All expected network resources are available.
```

### Version

8.12.0

### Steps to Reproduce

When integrating Sentry into a Flutter web project, using the print command causes an error:
```
Recursion during print() call. Abort adding print() call as Breadcrumb.  
```

### Expected Result

Breadcrumbs should log crash events without interfering with the print command.

### Actual Result

The print command fails and throws the following error in the console:
```
Recursion during print() call. Abort adding print() call as Breadcrumb.  
```

Would you like me to provide a possible solution for this issue?

### Are you willing to submit a PR?

None

### PR DESCRIPTION
**Pull request by denrase**
## :scroll: Description

Bug introduced in #2088 refactoring. There the addBreadcrumb call was not awaited, and we probably introduced this as the compiler issues a warning.

Bildschirmfoto 2025-01-28 um 15 13 00

## :bulb: Motivation and Context

Closes #2581
Relates to #2088

## :green_heart: How did you test it?

Ran in test app.

## :pencil: Checklist

- [x] I reviewed submitted code
- [ ] I added tests to verify changes
- [ ] No new PII added or SDK only sends newly added PII if `sendDefaultPii` is enabled
- [ ] I updated the docs if needed
- [x] All tests passing
- [ ] No breaking changes

### CODE REVIEW

File: dart/lib/src/sentry_run_zoned_guarded.dart [hunk 1]
```diff
@@ -61,7 +61,7 @@ class SentryRunZonedGuarded {
 
         try {
           _isPrinting = true;
-          await hub.addBreadcrumb(
+          hub.addBreadcrumb(
```
Comment (buenaflor) [inline dart/lib/src/sentry_run_zoned_guarded.dart]: we can wrap this in `unawaited` so it's not changed by accident

**Comment by buenaflor** [comment]
@denrase I think the unawaited change is still missing

**Comment by denrase** [comment]
@buenaflor ah sry, forgot to commit/push

File: CHANGELOG.md [hunk 2]
```diff
@@ -2,6 +2,9 @@
 
 ## Unreleased
 
+### Fixes
+
+- Fix print recursion detection ([#2624](https://github.com/getsentry/sentry-dart/pull/2624))
```
Comment (buenaflor) [inline CHANGELOG.md:7]:
```suggestion
- Fix print recursion detection ([#2624](https://github.com/getsentry/sentry-dart/pull/2624))

```

**Review by buenaflor — APPROVED** [review]
