### PR TITLE
Fix unsafe json access in `sentry_device`

### LINKED ISSUE #3301: loadContextsIntegration failed
### Platform

Flutter Mobile Android

### Obfuscation

Disabled

### Debug Info

Disabled

### Doctor

[sentry] [error] loadContextsIntegration failed
[sentry] _TypeError (type 'int' is not a subtype of type 'double?')

[sentry] [error] loadContextsIntegration failed
[sentry] _TypeError (type 'int' is not a subtype of type 'double?')
[sentry] #0      new SentryDevice.fromJson (package:sentry/src/protocol/sentry_device.dart:199:26)
sentry_device.dart:199
         #1      new Contexts.fromJson (package:sentry/src/protocol/contexts.dart:44:26)
contexts.dart:44
         #2      _mergeNativeWithLocalContexts (package:sentry_flutter/src/integrations/load_contexts_integration.dart:267:37)
load_contexts_integration.dart:267
         #3      _LoadContextsIntegrationEventProcessor.apply (package:sentry_flutter/src/integrations/load_contexts_integration.dart:120:7)
load_contexts_integration.dart:120
         <asynchronous suspension>
         #4      runEventProcessors (package:sentry/src/event_processor/run_event_processors.dart:26:52)
run_event_processors.dart:26
         <asynchronous suspension>
         #5      SentryClient.captureTransaction (package:sentry/src/sentry_client.dart:405:27)
sentry_client.dart:405
         <asynchronous suspension>
         #6      Hub.captureTransaction (package:sentry/src/hub.dart:615:22)
hub.dart:615
         <asynchronous suspension>
         #7      SentryTracer.finish (package:sentry/src/sentry_tracer.dart:161:7)
sentry_tracer.dart:161
         <asynchronous suspension>
         #8      SentryTracer._scheduleTimer.<anonymous closure> (package:sentry/src/sentry_tracer.dart:436:9)
sentry_tracer.dart:436
         <asynchronous suspension>

### Version

9.7.0

### Steps to Reproduce

every app launching in emulator PIXEL 8 PRO API 34

Future<void> main() async {
  SentryWidgetsFlutterBinding.ensureInitialized();
  await SentryFlutter.init(
    (options) {
      options.dsn =
          'https://blablablabla';
      // Set tracesSampleRate to 1.0 to capture 100% of transactions for tracing.
      // We recommend adjusting this value in production.
      options.tracesSampleRate = 1.0;
      // The sampling rate for profiling is relative to tracesSampleRate
      // Setting to 1.0 will profile 100% of sampled transactions:
      options.profilesSampleRate = 1.0;
    },
    appRunner: () => runApp(SentryWidget(child: const App())),
  );
}

### Expected Result

solution: make 'screen_density' as num

### Actual Result

Image

### Are you willing to submit a PR?

None

### PR DESCRIPTION
**Pull request by buenaflor**
## :scroll: Description

Currently accessing the json values is not type safe

## :bulb: Motivation and Context

Fixes #3301 

## :green_heart: How did you test it?
Unit tests

## :pencil: Checklist

- [x] I reviewed submitted code
- [x] I added tests to verify changes
- [x] No new PII added or SDK only sends newly added PII if `sendDefaultPii` is enabled
- [ ] I updated the docs if needed
- [ ] All tests passing
- [x] No breaking changes

## :crystal_ball: Next steps

Replace other protocol classes to use the new type safe access methods

### CODE REVIEW

File: packages/dart/lib/src/utils/type_safe_map_access.dart [hunk 1]
```diff
@@ -0,0 +1,86 @@
...
+  bool? getBool(String key) {
+    final value = this[key];
+    if (value == null) return null;
+    if (value is bool) return value;
+
+    // Handle numeric 0 and 1 as boolean values
+    if (value is num) {
+      if (value == 0) return false;
+      if (value == 1) return true;
+    }
```
Comment (buenaflor) [inline packages/dart/lib/src/utils/type_safe_map_access.dart]: the reason for this is when using FFI objective_c conversions bool are represented as 1 or 0 nums

File: packages/dart/lib/src/utils/type_safe_map_access.dart [hunk 2]
```diff
@@ -0,0 +1,86 @@
+import 'package:meta/meta.dart';
+import '../sentry.dart';
+import '../protocol/sentry_level.dart';
+
+/// Extension providing type-safe value extraction from JSON maps
+@internal
+extension TypeSafeMapExtension on Map<String, dynamic> {
+  /// Type-safe string extraction
+  String? getString(String key) {
```
Comment (denrase) [inline packages/dart/lib/src/utils/type_safe_map_access.dart]: Think we should name this `getStringOrNull`, so we have the intent in the naming. Dito for other methods.

File: packages/dart/lib/src/utils/type_safe_map_access.dart [hunk 3]
```diff
@@ -0,0 +1,86 @@
...
+    final value = this[key];
+    if (value == null) return null;
+    if (value is String) return value;
+
+    _logTypeMismatch(key, 'String', value.runtimeType.toString());
+    return null;
+  }
+
+  /// Type-safe int extraction with num support
+  int? getInt(String key) {
```
Comment (denrase) [inline packages/dart/lib/src/utils/type_safe_map_access.dart]: We could also think about making this a generic function instead of multiple.

```dart
T? getValueOrNull<T>(String key)
```

**Review by denrase — CHANGES_REQUESTED** [review]

File: packages/dart/lib/src/utils/type_safe_map_access.dart (hunk 3 above)
Comment (buenaflor) [reply packages/dart/lib/src/utils/type_safe_map_access.dart]: my personal preference would be to be a bit more verbose but I dont mind doing it as generic as well

File: packages/dart/lib/src/utils/type_safe_map_access.dart (hunk 2 above)
Comment (buenaflor) [reply packages/dart/lib/src/utils/type_safe_map_access.dart]: makes sense 👍

File: packages/dart/lib/src/utils/type_safe_map_access.dart (hunk 3 above)
Comment (buenaflor) [reply packages/dart/lib/src/utils/type_safe_map_access.dart]: updated it

File: packages/dart/lib/src/utils/type_safe_map_access.dart [hunk 4]
```diff
@@ -0,0 +1,88 @@
+import 'package:meta/meta.dart';
+import '../sentry.dart';
+import '../protocol/sentry_level.dart';
+
+/// Extension providing type-safe value extraction from JSON maps
+@internal
+extension TypeSafeMapExtension on Map<String, dynamic> {
+  /// Generic, type-safe extraction with a few built-in coercions:
```
Comment (denrase) [inline packages/dart/lib/src/utils/type_safe_map_access.dart:8]: ❤️

**Review by denrase — APPROVED** [review]
