### PR TITLE
Testflight

### LINKED ISSUE #387: During CI, publish iOS app to TestFlight
This setup exists on `sentry-cocoa` and is useful to do some "manual testing" before a release without the need to build locally and run on a device.

A failed attempt here: https://github.com/getsentry/sentry-dart/pull/340

Potential to extra the work done on https://github.com/getsentry/sentry-cocoa into a git repo that can be added via gittree or submodule to be reused/maintained across repos. We'd like to see this in also with other repos such as Unity, Flutter, Cordova, React Native and Xamarin.

### PR DESCRIPTION
**Pull request by denrase**
#skip-changelog

## :scroll: Description

Setup an action to upload the iOS sample app to TestFlight.

## :bulb: Motivation and Context

Closes #387

## :pencil: Checklist

- [x] I reviewed submitted code
- [ ] I added tests to verify changes
- [ ] No new PII added or SDK only sends newly added PII if `sendDefaultPii` is enabled
- [ ] I updated the docs if needed
- [ ] All tests passing
- [x] No breaking changes

### CODE REVIEW

**Comment by stefanosiano** [comment]
hey @denrase 
is there a braking change here? Why is it for v8?

File: scripts/ci-select-xcode.sh [hunk 1]
```diff
@@ -0,0 +1,14 @@
...
+
+# For available Xcode versions see:
+# - https://github.com/actions/virtual-environments/blob/main/images/macos/macos-11-Readme.md#xcode
+# - https://github.com/actions/runner-images/blob/main/images/macos/macos-12-Readme.md
+# - https://github.com/actions/runner-images/blob/main/images/macos/macos-13-Readme.md
+
+set -euo pipefail
+
+# 14.3 is the default
+XCODE_VERSION="${1:-14.3}"
```
Comment (philipphofmann) [inline scripts/ci-select-xcode.sh]: `h`: We must use Xcode 15.x, because in a couple of weeks all apps uploaded to TestFlight must be build with Xcode 15. You could also use https://github.com/XcodesOrg/xcodes to replace this script, as this is now installed per default for the GH action ima `macos-13`, see https://github.com/actions/runner-images/blob/main/images/macos/macos-13-Readme.md#tools.

**Comment by denrase** [comment]
@stefanosiano Needs iOS 12 to build, which we bump the SDK to in v8.

**Comment by denrase** [comment]
@buenaflor Think we can merge this. WDYT?

**Review by buenaflor — APPROVED** [review]
Looks good, only thing left is to fix the red ci
