### PR TITLE
Fix: Context Escape with `ScopeCallback`

### LINKED ISSUE #921: Context escape with `ScopeCallback`
The callback `typedef ScopeCallback = void Function(Scope);`

Should be:

`typedef ScopeCallback = FutureOr<void> Function(Scope);`

Otherwise, there's a context scope because Scope has async methods but you can't await for `configureScope`.

`void configureScope(ScopeCallback callback)`

Should be:

`FutureOr<void> configureScope(ScopeCallback callback)`

Executions of the `ScopeCallback? withScope` should also be awaited otherwise the same problem happens.

Add changes to https://docs.sentry.io/platforms/dart/migration/#migrating-from-sentry-65x-to-sentry-66x

### PR DESCRIPTION
**Pull request by denrase**
### ScopeCallback

- Change `ScopeCallback` from `void Function(Scope)` to `FutureOr<void> Function(Scope)`

### configureScope

- Change `static void configureScope(ScopeCallback callback)` to `static FutureOr<void> configureScope(ScopeCallback callback)` in `Sentry` class.
- Change `void configureScope(ScopeCallback callback)` to `FutureOr<void> configureScope(ScopeCallback callback)` in `Hub` class.

### clone

- Change `static Hub clone()` to `static Future<Hub> clone()` in `Sentry` class.
- Change `static Hub clone()` to `static Future<Hub> clone()` in `Hub/HubAdapter` classes.
- Change `Scope clone()` to `Future<Scope> clone()` in `Scope ` class.

### addBreadcrumb

- Change `static void addBreadcrumb(Breadcrumb crumb, {dynamic hint})` to `static  Future<void> addBreadcrumb(Breadcrumb crumb, {dynamic hint})` in `Scope` class.
- Change `void addBreadcrumb(Breadcrumb crumb, {dynamic hint})` to `Future<void> addBreadcrumb(Breadcrumb crumb, {dynamic hint})` in `Hub/HubAdapter` class.

### Other

- Remove internal `async` methods in `SentryNavigatorObserver`, as they were only ever called from sync methods.

## :bulb: Motivation and Context

Closes #921

## :green_heart: How did you test it?

Ran tests.

## :pencil: Checklist

- [x] I reviewed submitted code
- [ ] I added tests to verify changes
- [ ] I updated the docs if needed
- [x] All tests passing
- [ ] No breaking changes

### CODE REVIEW

File: dart/lib/src/hub.dart [hunk 1]
```diff
@@ -317,7 +318,7 @@ class Hub {
   }
 
   /// Configures the scope through the callback.
-  void configureScope(ScopeCallback callback) {
+  FutureOr<void> configureScope(ScopeCallback callback) {
```
Comment (marandaneto) [inline dart/lib/src/hub.dart]: `Sentry.configureScope` also has to change, not only the `Hub` class, likely the NoOp classes, etc.

Comment (marandaneto) [reply dart/lib/src/hub.dart]: Maybe `Scope#clone` also has to change since it calls the setters that are `Future`.
I'd double-check every interaction with the methods that are now `Future` or `FutureOr`

Comment (marandaneto) [reply dart/lib/src/hub.dart]: I also found this https://github.com/getsentry/sentry-dart/issues/926 but its a different issue and can be addressed in a different PR

File: dart/example_web/web/main.dart [hunk 2]
```diff
@@ -21,7 +21,7 @@ Future<void> main() async {
   );
 }
 
-void runApp() {
+void runApp() async {
```
Comment (marandaneto) [inline dart/example_web/web/main.dart]:
```suggestion
Future<void> runApp() async {
```

File: dart/lib/src/hub_adapter.dart [hunk 3]
```diff
@@ -1,4 +1,5 @@
 import 'dart:async';
+import 'dart:ffi';
```
Comment (marandaneto) [inline dart/lib/src/hub_adapter.dart]: This is wrong I believe.

File: flutter/lib/src/navigation/sentry_navigator_observer.dart [hunk 4]
```diff
@@ -153,7 +151,7 @@ class SentryNavigatorObserver extends RouteObserver<PageRoute<dynamic>> {
     }
   }
 
-  Future<void> _startTransaction(String? name, Object? arguments) async {
+  void _startTransaction(String? name, Object? arguments) {
```
Comment (marandaneto) [inline flutter/lib/src/navigation/sentry_navigator_observer.dart]: Why did we change this? seems not related to this PR.

Comment (denrase) [reply flutter/lib/src/navigation/sentry_navigator_observer.dart]: One of the tests was failing, as one of the methods called here internally now returns a future. Woking on this I saw that none of the private async functions here is awaited, as it is only called internally from sync API. I'm not sure anymore why we went async here, seems redundant?

Comment (marandaneto) [reply flutter/lib/src/navigation/sentry_navigator_observer.dart]: `beginNativeFramesCollection` is async, and we want the frames from that time, if we don't `await`, this function can be executed later and the frames are not the same anymore.
So It should be `async` but awaited.
We also call `configureScope` which is now async as well, another reason to be async.

**Comment by marandaneto** [comment]
@denrase PR is marked ready to review but there are open issues still.
E.g. https://github.com/getsentry/sentry-dart/pull/925#discussion_r913012781

File: dart/example_web/web/main.dart [hunk 5]
```diff
@@ -21,7 +21,7 @@ Future<void> main() async {
   );
 }
 
-void runApp() {
+FutureOr<void> runApp() async {
```
Comment (marandaneto) [inline dart/example_web/web/main.dart]:
```suggestion
Future<void> runApp() async {
```

File: dart/lib/src/hub.dart [hunk 6]
```diff
@@ -275,13 +276,13 @@ class Hub {
   }
 
   /// Clones the Hub
-  Hub clone() {
+  FutureOr<Hub> clone() async {
```
Comment (marandaneto) [inline dart/lib/src/hub.dart]:
```suggestion
  Future<Hub> clone() async {
```

Only `ScopeCallback` should be FutureOr because the user can define either an async or sync method.
`clone` is always `async`.

File: dart/lib/src/hub_adapter.dart [hunk 7]
```diff
@@ -78,14 +78,14 @@ class HubAdapter implements Hub {
       );
 
   @override
-  Hub clone() => Sentry.clone();
+  FutureOr<Hub> clone() async => await Sentry.clone();
```
Comment (marandaneto) [inline dart/lib/src/hub_adapter.dart]:
```suggestion
  Future<Hub> clone() async => await Sentry.clone();
```

File: dart/lib/src/scope.dart [hunk 8]
```diff
@@ -381,25 +381,25 @@ class Scope {
   }
 
   /// Clones the current Scope
-  Scope clone() {
+  FutureOr<Scope> clone() async {
```
Comment (marandaneto) [inline dart/lib/src/scope.dart]:
```suggestion
  Future<Scope> clone() async {
```

File: dart/lib/src/sentry.dart [hunk 9]
```diff
@@ -197,11 +197,11 @@ class Sentry {
...
 
   /// Configures the scope through the callback.
-  static void configureScope(ScopeCallback callback) =>
-      _hub.configureScope(callback);
+  static FutureOr<void> configureScope(ScopeCallback callback) async =>
+      await _hub.configureScope(callback);
 
   /// Clones the current Hub
-  static Hub clone() => _hub.clone();
+  static FutureOr<Hub> clone() async => await _hub.clone();
```
Comment (marandaneto) [inline dart/lib/src/sentry.dart]:
```suggestion
  static Future<Hub> clone() async => await _hub.clone();
```

File: dart/test/hub_test.dart [hunk 10]
```diff
@@ -170,7 +170,7 @@ void main() {
         bindToScope: true,
       );
 
-      hub.configureScope((Scope scope) {
+      await hub.configureScope((Scope scope) {
```
Comment (marandaneto) [inline dart/test/hub_test.dart:173]: I'd add a new test that `hub.configureScope` also takes a non-async method.

Comment (denrase) [reply dart/test/hub_test.dart:173]: Not sure I understand. The one here is a non-async method as param.

File: flutter/test/sentry_navigator_observer_test.dart [hunk 11]
```diff
@@ -57,7 +59,10 @@ void main() {
 
       sut.didPush(currentRoute, null);
 
-      expect(mockNativeChannel.numberOfBeginNativeFramesCalls, 1);
+      // Handle internal async method calls.
+      await Future.delayed(const Duration(milliseconds: 10), () {
+        expect(mockNativeChannel.numberOfBeginNativeFramesCalls, 1);
+      });
```
Comment (marandaneto) [inline flutter/test/sentry_navigator_observer_test.dart:65]: We can likely remove this `delayed` now since we can await the call.

File: dart/test/hub_test.dart (hunk 10 above)
Comment (marandaneto) [reply dart/test/hub_test.dart:173]: Sorry, I meant, we should add a test that tests an async callback for `configureScope`.
E.g.

```
      await hub.configureScope((Scope scope) async {
        // do something with async work because the method is `async`
      });
```

Comment (marandaneto) [reply dart/test/hub_test.dart:173]: It could be .e.g. `await Future.delayed(Duration(seconds: 1));` but with just a few millis.

**Comment by marandaneto** [comment]
`Hub#addBreadcrumb` should also return a `Future<void>` since it calls `Scope#addBreadcrumb`
Worth enabling `unawaited_futures: true` lint rule and double-check that, maybe there are more methods that we've forgotten to change it.

File: flutter/test/sentry_navigator_observer_test.dart (hunk 11 above)
Comment (denrase) [reply flutter/test/sentry_navigator_observer_test.dart:65]: Don't think we can here? `didPush` is a sync method and we can't change the signature, as we are implementing an interface. Or am i missing something here?

Comment (marandaneto) [reply flutter/test/sentry_navigator_observer_test.dart:65]: Oh indeed, I missed that.

File: dart/test/hub_test.dart [hunk 12]
```diff
@@ -114,7 +114,7 @@ void main() {
       expect(capturedEvent.event.contexts.trace, isNotNull);
     });
 
-    test('Expando does not throw when exception type is not supported',
+    test('Expand does not throw when exception type is not supported',
```
Comment (marandaneto) [inline dart/test/hub_test.dart]: That's `Expando` that comes from `dart.core`

Comment (denrase) [reply dart/test/hub_test.dart]: 🤦

**Comment by denrase** [comment]
CI issue occurs from running `pana`. Can't seem to call `FutureOr<void> configureScope(ScopeCallback callback)` in `SentryNavigatorObserver` with `await`. Works if calling without `await`, which we technically don't need, as our closures are not async, but this might affect others when calling the new API? I haven't seen this error before, all tests run as expected. Maybe @ueman has an idea why this is reported as an error?

Bildschirmfoto 2022-07-05 um 17 14 26

**Comment by marandaneto** [comment]
I believe it could be because of how `pana` runs again.
The public API changed but pana checks the latest published version instead the local version.
https://github.com/dart-lang/pana/issues/1020
In this case, we can ignore it as long as `pana` runs locally just fine.

**Review by marandaneto — APPROVED** [review]
