### PR TITLE
Fix: Web examples

### LINKED ISSUE #432: Set base path for Flutter Web example
The Flutter web example should have a different base path because it is hosted at a non root location.

See https://flutter.dev/docs/development/ui/navigation/url-strategies#hosting-a-flutter-app-at-a-non-root-location

The Flutter Web example is hosted at https://getsentry.github.io/sentry-dart/

### PR DESCRIPTION
**Pull request by ueman**
## :scroll: Description
This fixes some issues with the web examples.

_#skip-changelog_

## :bulb: Motivation and Context
Closes https://github.com/getsentry/sentry-dart/issues/432
Also removes workaround mentioned by https://github.com/getsentry/sentry-dart/issues/431

## :green_heart: How did you test it?
I run the examples

## :pencil: Checklist

- [x] I reviewed submitted code
- [ ] I added tests to verify changes
- [ ] I updated the docs if needed
- [x] All tests passing
- [x] No breaking changes

### CODE REVIEW

File: dart/example_web/web/main.dart [hunk 1]
```diff
@@ -87,8 +87,7 @@ Future<void> captureException() async {
     print('\nReporting the following stack trace: ');
     final sentryId = await Sentry.captureException(
       error,
-      stackTrace: stackTrace
-          .toString() /* on safari (14.0) passing a stacktrace object fails */,
+      stackTrace: stackTrace,
```
Comment (bruno-garcia) [inline dart/example_web/web/main.dart:90]: The Safari issue is just gone?

**Review by bruno-garcia — APPROVED** [review]

File: dart/example_web/web/main.dart (hunk 1 above)
Comment (ueman) [reply dart/example_web/web/main.dart:90]: Yes, I had a good test session yesterday and everything works as expected.
