### PR TITLE
Sentry Supabase Integration

### LINKED ISSUE #2727: Supabase Support
### Problem Statement

Sentry's Flutter SDK does not have OOTB support for Supabase features. Supabase is famously a new service for your postgres DB, but it does much more today.

in order of what the SDK should support, and can be broken into independently shippable features:
- support of the [supabase_flutter](https://supabase.com/docs/reference/dart/start) library for all CRUD interactions with a database [Supabase Flutter Client](https://pub.dev/packages/supabase_flutter)

### Solution Brainstorm

There is a [3rd party integration](https://github.com/supabase-community/sentry-integration-js) for their Node.js library, for reference.

### Are you willing to submit a PR?

None

### PR DESCRIPTION
**Pull request by denrase**
## :scroll: Description

Supabase instrumentation for database operations (no auth instrumentation)

- [x] Breadcrumbs
- [x] Body Redaction
- [x] Tracing
- [x] Errors
- [x] PII (Body, Query)

## :bulb: Motivation and Context

Closes #2727

## :green_heart: How did you test it?

Unit tests.

## :pencil: Checklist

- [x] I reviewed submitted code
- [x] I added tests to verify changes
- [x] No new PII added or SDK only sends newly added PII if `sendDefaultPii` is enabled
- [ ] I updated the docs if needed
- [x] All tests passing
- [x] No breaking changes

### CODE REVIEW

File: supabase/lib/src/sentry_supabase_tracing_client.dart [hunk 1]
```diff
@@ -0,0 +1,76 @@
...
+    // ignore: invalid_use_of_internal_member
+    if (supabaseRequest.query.isNotEmpty && _hub.options.sendDefaultPii) {
+      span.setData('db.query', supabaseRequest.query);
+    }
+    // ignore: invalid_use_of_internal_member
+    if (supabaseRequest.body != null && _hub.options.sendDefaultPii) {
+      span.setData('db.body', supabaseRequest.body);
+    }
+    span.setData('op', 'db.${supabaseRequest.operation.value}');
+    span.setData('origin', 'auto.db.supabase');
```
Comment (buenaflor) [inline supabase/lib/src/sentry_supabase_tracing_client.dart]: pls add `auto.db.supabase` to the const file `sentry_trace_origins.dart`

File: supabase/lib/src/sentry_supabase_tracing_client.dart [hunk 2]
```diff
@@ -0,0 +1,76 @@
...
+  void close() {
+    _innerClient.close();
+  }
+
+  // Helper
+
+  ISentrySpan? _createSpan(SentrySupabaseRequest supabaseRequest) {
+    final description = 'from(${supabaseRequest.table})';
+
+    final span = _hub.startTransaction(
```
Comment (buenaflor) [inline supabase/lib/src/sentry_supabase_tracing_client.dart]: we usually don't create transactions in integrations so I'd just use `_hub.getSpan`

File: supabase/lib/src/sentry_supabase_tracing_client.dart [hunk 3]
```diff
@@ -0,0 +1,76 @@
...
+    }
+    // ignore: invalid_use_of_internal_member
+    if (supabaseRequest.query.isNotEmpty && _hub.options.sendDefaultPii) {
+      span.setData('db.query', supabaseRequest.query);
+    }
+    // ignore: invalid_use_of_internal_member
+    if (supabaseRequest.body != null && _hub.options.sendDefaultPii) {
+      span.setData('db.body', supabaseRequest.body);
+    }
+    span.setData('op', 'db.${supabaseRequest.operation.value}');
```
Comment (buenaflor) [inline supabase/lib/src/sentry_supabase_tracing_client.dart]:
```suggestion
    span.setData('db.operation', supabaseRequest.operation.value);
```

other way around I think

**Review by buenaflor — COMMENTED** [review]
Quick pass, I'll have a closer look later

File: supabase/lib/src/sentry_supabase_client.dart [hunk 4]
```diff
@@ -0,0 +1,87 @@
...
+  final bool _tracing;
+  final bool _errors;
+
+  Client _innerClient;
+  final Hub _hub;
+
+  SentrySupabaseClient({
+    bool breadcrumbs = true,
+    bool tracing = true,
+    bool errors = true,
```
Comment (buenaflor) [inline supabase/lib/src/sentry_supabase_client.dart]: what about 

```dart
final bool enableBreadcrumbs;
final bool enableTracing;
final bool enableErrorReporting;
```

File: supabase/lib/src/sentry_supabase_tracing_client.dart (hunk 3 above)
Comment (buenaflor) [inline supabase/lib/src/sentry_supabase_tracing_client.dart]: `db.system` with `postgres` is missing

File: supabase/lib/src/sentry_supabase_request.dart [hunk 5]
```diff
@@ -0,0 +1,145 @@
...
+          return Operation.upsert;
+        } else {
+          return Operation.insert;
+        }
+      case 'PATCH':
+        return Operation.update;
+      case 'DELETE':
+        return Operation.delete;
+      default:
+        return Operation.select; // Should never happen.
```
Comment (buenaflor) [inline supabase/lib/src/sentry_supabase_request.dart]: should we use an unknown?

File: supabase/lib/src/sentry_supabase_request.dart [hunk 6]
```diff
@@ -0,0 +1,145 @@
...
+            (value) => _translateFiltersIntoMethods(entry.key, value),
+          ),
+        )
+        .toList();
+  }
+
+  static Map<String, dynamic>? _readBody(String table, BaseRequest request) {
+    final bodyString =
+        request is Request && request.body.isNotEmpty ? request.body : null;
+    final body = bodyString != null ? jsonDecode(bodyString) : null;
```
Comment (buenaflor) [inline supabase/lib/src/sentry_supabase_request.dart]: should we introduce some limit? or does the supabase SDK already handle big request bodies?

File: supabase/lib/src/sentry_supabase_tracing_client.dart [hunk 7]
```diff
@@ -0,0 +1,76 @@
...
+  }
+
+  // Helper
+
+  ISentrySpan? _createSpan(SentrySupabaseRequest supabaseRequest) {
+    final description = 'from(${supabaseRequest.table})';
+
+    final span = _hub.startTransaction(
+      description,
+      'db.${supabaseRequest.operation.value}',
```
Comment (buenaflor) [inline supabase/lib/src/sentry_supabase_tracing_client.dart]: we can do span op: `db.sql.query` and description to be the full supabase query

File: supabase/lib/src/sentry_supabase_tracing_client.dart [hunk 8]
```diff
@@ -0,0 +1,76 @@
...
+    } catch (e) {
+      span?.throwable = e;
+      span?.status = SpanStatus.internalError();
+      rethrow;
+    } finally {
+      await span?.finish();
+    }
+
+    return response;
+  }
```
Comment (buenaflor) [inline supabase/lib/src/sentry_supabase_tracing_client.dart:50]: I assume this is also triggered for auth requests? we gotta make sure this only handles database operations

auth tracing should be separate

File: supabase/lib/src/sentry_supabase_tracing_client.dart (hunk 7 above)
Comment (denrase) [reply supabase/lib/src/sentry_supabase_tracing_client.dart]: I'm not sure i understand. Could you give me an example for this case?

Comment (buenaflor) [reply supabase/lib/src/sentry_supabase_tracing_client.dart]: Something like:
```
description: 'SELECT * FROM TABLE'
op: 'db.sql.query'
```

Comment (buenaflor) [reply supabase/lib/src/sentry_supabase_tracing_client.dart]: following the conventions: https://develop.sentry.dev/sdk/telemetry/traces/span-operations/#database

Comment (denrase) [reply supabase/lib/src/sentry_supabase_tracing_client.dart]: Added support for this, including most common operations/clauses.

File: supabase/lib/src/sentry_supabase_tracing_client.dart (hunk 8 above)
Comment (denrase) [reply supabase/lib/src/sentry_supabase_tracing_client.dart:50]: Now only handling the restful requests, ignoring everything else (including auth).

**Comment by buenaflor** [comment]
Will make another review pass soon

**Comment by buenaflor** [comment]
@denrase pls take a look at cursor's comment I think the concern is valid since we'd be doing this for every request

**Comment by denrase** [comment]
@buenaflor 🤦‍♂️

File: supabase/lib/src/sentry_supabase_request.dart (hunk 6 above)
Comment (denrase) [reply supabase/lib/src/sentry_supabase_request.dart]: added max size from options and also defaultpii flag

**Comment by buenaflor** [comment]
@denrase could you have a look at cursor comments pls

**Comment by denrase** [comment]
@buenaflor Issues should be addressed now.

File: packages/supabase/lib/src/sentry_supabase_tracing_client.dart [hunk 9]
```diff
@@ -0,0 +1,87 @@
...
+    if (supabaseRequest.query.isNotEmpty && _hub.options.sendDefaultPii) {
+      span.setData('db.query', supabaseRequest.query);
+    }
+    // ignore: invalid_use_of_internal_member
+    if (supabaseRequest.body != null && _hub.options.sendDefaultPii) {
+      span.setData('db.body', supabaseRequest.body);
+    }
+    span.setData('db.operation', supabaseRequest.operation.value);
+    span.setData('db.sql.query', supabaseRequest.generateSqlQuery());
+    span.setData('db.system', 'postgres');
```
Comment (buenaflor) [inline packages/supabase/lib/src/sentry_supabase_tracing_client.dart]:
```suggestion
    span.setData('db.system', 'postgresql');
```

Comment (buenaflor) [inline packages/supabase/lib/src/sentry_supabase_tracing_client.dart]: we can put all these constant span data key/values into the `constants.dart` file within `SentrySpanData`

Comment (buenaflor) [reply packages/supabase/lib/src/sentry_supabase_tracing_client.dart]: we can make use of this constants file also for the other constants used in this PR

File: .github/workflows/diagrams.yml [hunk 10]
```diff
@@ -59,6 +59,10 @@ jobs:
         working-directory: ./packages/firebase_remote_config
         run: lakos . -i "{test/**,example/**}" | dot -Tsvg -o class-diagram.svg
 
+      - name: supabase
+        working-directory: ./packages/supabase
+        run: lakos . -i "{test/**,example/**}" | dot -Tsvg -o class-diagram.svg
+
```
Comment (buenaflor) [inline .github/workflows/diagrams.yml:65]: honestly I keep forgetting this diagram exists 😓

File: packages/dart/lib/src/constants.dart [hunk 11]
```diff
@@ -16,8 +16,19 @@ class SentrySpanOperations {
...
+  static const String dbSchemaKey = 'db.schema';
+  static const String dbTableKey = 'db.table';
+  static const String dbUrlKey = 'db.url';
+  static const String dbSdkKey = 'db.sdk';
+  static const String dbQueryKey = 'db.query';
+  static const String dbBodyKey = 'db.body';
+  static const String dbOperationKey = 'db.operation';
+  static const String httpResponseStatusCodeKey = 'http.response.status_code';
+  static const String httpResponseContentLengthKey =
+      'http.response_content_length';
```
Comment (buenaflor) [inline packages/dart/lib/src/constants.dart:28]: thx 🙏

File: packages/supabase/lib/src/sentry_supabase_error_client.dart [hunk 12]
```diff
@@ -0,0 +1,89 @@
...
+          _captureException(
+            null,
+            null,
+            request,
+            response,
+            supabaseRequest,
+          ),
+        );
+      }
+      return response;
```
Comment (buenaflor) [inline packages/supabase/lib/src/sentry_supabase_error_client.dart:46]: do you think it makes sense to be able to configure this? not sure if all folks would consider a 4xx an error

File: packages/supabase/lib/src/constants.dart [hunk 13]
```diff
@@ -0,0 +1,2 @@
+const String integrationName = 'sentrySupabaseTracing';
```
Comment (buenaflor) [inline packages/supabase/lib/src/constants.dart]: I think we should split it up:
- `SupabaseTracing`
- `SupabaseBreadcrumbs`
- `SupabaseErrors`

and add each one to `sdk.integrations` if the respectiv supabase clients are enabled

**Review by buenaflor — COMMENTED** [review]
looks good! only a few comments left

**Comment by buenaflor** [comment]
cloudflare has an outage so lots of tests are failing now that depend on external downloads

File: packages/supabase/lib/src/constants.dart (hunk 13 above)
Comment (buenaflor) [reply packages/supabase/lib/src/constants.dart]: that way we know exactly what users enabled

File: .github/workflows/diagrams.yml (hunk 10 above)
Comment (denrase) [reply .github/workflows/diagrams.yml:65]: TBH, we could think about removing this, no? My hunch is nobody uses it and it's outdated anyway. We could leave it as a dev option so we can generate it locally to get an overview, but remove the checked in files. WDYT?

File: packages/supabase/lib/src/sentry_supabase_error_client.dart (hunk 12 above)
Comment (denrase) [reply packages/supabase/lib/src/sentry_supabase_error_client.dart:46]: I'll check what we do in other places throughout the SDK and align.

Comment (denrase) [reply packages/supabase/lib/src/sentry_supabase_error_client.dart:46]: Added `failedRequestStatusCodes`

File: packages/supabase/lib/src/sentry_supabase_request.dart [hunk 14]
```diff
@@ -0,0 +1,314 @@
...
+    'plfts': 'plain',
+    'phfts': 'phrase',
+    'wfts': 'websearch',
+    'not': 'not',
+  };
+
+  static String _translateFiltersIntoMethods(String key, String query) {
+    if (query.isEmpty || query == '*') {
+      return 'select(*)';
+    }
```
[the remark this answers is not in the document]
Comment (denrase) [reply packages/supabase/lib/src/sentry_supabase_request.dart:156]: Can't verify if `?id=` with empty value is a valid request.

**Comment by denrase** [comment]
@buenaflor Last week I created a sample project with Flutter + Subase as an evaluation. I wan't to try this out before we merge.

**Comment by buenaflor** [comment]
sounds good, looks good to me now

let me know if you thinks its ready

**Comment by denrase** [comment]
@buenaflor Ok, looking good with the sample app. The error client is being called and breadcrumbs created.

Bildschirmfoto 2025-11-19 um 13 41 38

Only thing i saw that the hub does not have a span, so we can't create one. Dunno if this is supposed to be like that? We have the same logic in other integrations.

Bildschirmfoto 2025-11-19 um 13 42 42

**Comment by buenaflor** [comment]
> Only thing i saw that the hub does not have a span, so we can't create one. Dunno if this is supposed to be like that? We have the same logic in other integrations.

do you have a running transaction with `bindToScope = true`?

**Comment by buenaflor** [comment]
We discussed that this works now

File: .github/workflows/diagrams.yml (hunk 10 above)
Comment (buenaflor) [reply .github/workflows/diagrams.yml:65]: yea imo we can remove it in another PR

**Review by buenaflor — APPROVED** [review]
