### PR TITLE
Platform Exception Event Processor

### LINKED ISSUE #1231: Add tags for `PlatformException`
A lot of plugins just throw a [`PlatformException`](https://api.flutter.dev/flutter/services/PlatformException-class.html). That makes it hard to distinguish between those exceptions because they're used everywhere.

In order to better filter `PlatformExceptions` on Sentry, it would be nice to be able to filter based on [`PlatformException.code`](https://api.flutter.dev/flutter/services/PlatformException/code.html) and maybe on [`PlatformException.message`](https://api.flutter.dev/flutter/services/PlatformException/message.html) (though not to sure about this). Therefore, I suggest to add those fields as tags to events with a `PlatformException`.

### PR DESCRIPTION
**Pull request by denrase**
## :scroll: Description

- Adds an event processor that enriches `SentryEvent.mechanism` with `PlatformException` code and message. 

## :bulb: Motivation and Context

Closes #1231

## :green_heart: How did you test it?

Unit tests.

## :pencil: Checklist

- [x] I reviewed submitted code
- [x] I added tests to verify changes
- [x] No new PII added or SDK only sends newly added PII if `sendDefaultPii` is enabled
- [ ] I updated the docs if needed
- [x] All tests passing
- [x] No breaking changes

## :crystal_ball: Next steps

Should we also create a mechanism if it's null on the `SentryException`?

### CODE REVIEW

**Comment by denrase** [comment]
@marandaneto Hope i interpreted the discussion on https://github.com/getsentry/sentry-dart/issues/1231 correctly.

File: flutter/lib/src/event_processor/platform_exception_event_processor.dart [hunk 1]
```diff
@@ -0,0 +1,36 @@
...
+    final data = Map<String, dynamic>.from(
+      sentryException.mechanism?.data ?? {},
+    );
+    data['platformException'] = {'code': platformException.code};
+    if (platformException.message != null) {
+      data['platformException']['message'] = platformException.message;
+    }
+    return sentryException.copyWith(
+      mechanism: sentryException.mechanism?.copyWith(data: data),
+    );
```
Comment (marandaneto) [inline flutter/lib/src/event_processor/platform_exception_event_processor.dart]: This will only work if the event has a `Mechanism` which is not the case for manually captured events.
Maybe if there's not one, we create a new mechanism?

File: flutter/lib/src/event_processor/platform_exception_event_processor.dart [hunk 2]
```diff
@@ -0,0 +1,36 @@
...
+
+  SentryException _enrich(
+      SentryException sentryException, PlatformException platformException) {
+    final data = Map<String, dynamic>.from(
+      sentryException.mechanism?.data ?? {},
+    );
+    data['platformException'] = {'code': platformException.code};
+    if (platformException.message != null) {
+      data['platformException']['message'] = platformException.message;
+    }
```
Comment (marandaneto) [inline flutter/lib/src/event_processor/platform_exception_event_processor.dart]: If we put it under the `data` field, we need to be sure that this is possible to make it searchable on Sentry/Snuba.
[Most likely yes](https://github.com/getsentry/sentry/blob/abb44c51917828ad67d0654f4192bbb0c3873a96/src/sentry/rules/conditions/event_attribute.py#L120-L131).
Since the `error.handled` search actually checks the `mechanism` metadata.

Comment (marandaneto) [inline flutter/lib/src/event_processor/platform_exception_event_processor.dart]: Maybe we don't need to put the fields under `platformException` but rather directly in the `data` field, or is there a reason for the collision? likely not.

Comment (denrase) [reply flutter/lib/src/event_processor/platform_exception_event_processor.dart]: It was just to add some context by being descriptive and also collision, yes. But if we call the keys `platformExceptionCode` & `platformExceptionMessage` we should be fine.

Comment (denrase) [reply flutter/lib/src/event_processor/platform_exception_event_processor.dart]: The data shows up on sentry, but i'm not familiar how to search for it.

Bildschirm­foto 2023-02-28 um 14 14 42

Comment (marandaneto) [reply flutter/lib/src/event_processor/platform_exception_event_processor.dart]: Apparently, this becomes a tag so it should work OOTB.

Comment (marandaneto) [reply flutter/lib/src/event_processor/platform_exception_event_processor.dart]: nvm it does not work, `error.mechanism:platformException ` works but you can't search for the `code` and `message`.
This has to be implemented directly in sentry by expanding the `error.mechanism` queries.
We can do that later on.
Quick question, do we know if the `code` is actually one of ISO C99, POSIX.1-2001 or POSIX.1-2008. or just a hardcoded in the Flutter framework?
I'm wondering if this should fit the `meta` field of the `mechanism`.
https://develop.sentry.dev/sdk/event-payloads/types/#typedef-CError
I guess it can be anything?

**Review by marandaneto — APPROVED** [review]
Approving it but I am double-checking https://github.com/getsentry/sentry-dart/pull/1297#discussion_r1121691325 before merging.
Thanks.

File: flutter/lib/src/event_processor/platform_exception_event_processor.dart [hunk 3]
```diff
@@ -0,0 +1,38 @@
...
+  }
+
+  SentryException _enrich(
+      SentryException sentryException, PlatformException platformException) {
+    final data = Map<String, dynamic>.from(
+      sentryException.mechanism?.data ?? {},
+    );
+    data['platformExceptionCode'] = platformException.code;
+    if (platformException.message != null) {
+      data['platformExceptionMessage'] = platformException.message;
```
Comment (marandaneto) [inline flutter/lib/src/event_processor/platform_exception_event_processor.dart]:
```suggestion
    data['code'] = platformException.code;
    if (platformException.message != null) {
      data['message'] = platformException.message;
```

We can be more generic here, the `mechanism` has a type already.
[PHP](https://github.com/getsentry/sentry-php/pull/1451) also uses `code`.
If there's already a mechanism, the type of the exception will be `PlatformException` anyway.

File: flutter/test/event_processor/platform_exception_event_processor_test.dart [hunk 4]
```diff
@@ -0,0 +1,62 @@
...
+      var event = SentryEvent(exceptions: [sentryException]);
+
+      final sut = fixture.getSut();
+      event = (await sut.apply(event))!;
+
+      expect(event.exceptions?.first.mechanism?.data["platformExceptionCode"],
+          "fixture-code");
+      expect(
+          event.exceptions?.first.mechanism?.data["platformExceptionMessage"],
+          "fixture-message");
```
Comment (marandaneto) [inline flutter/test/event_processor/platform_exception_event_processor_test.dart]:
```suggestion
      expect(event.exceptions?.first.mechanism?.data["code"],
          "fixture-code");
      expect(
          event.exceptions?.first.mechanism?.data["message"],
          "fixture-message");
```

File: flutter/lib/src/event_processor/platform_exception_event_processor.dart (hunk 2 above)
Comment (marandaneto) [reply flutter/lib/src/event_processor/platform_exception_event_processor.dart]: I am checking internally if we can add it under the `meta`, let's not merge this for now.

Comment (ueman) [reply flutter/lib/src/event_processor/platform_exception_event_processor.dart]: > Quick question, do we know if the code is actually one of ISO C99, POSIX.1-2001 or POSIX.1-2008. or just a hardcoded in the Flutter framework?

It's not. It is a free form string and pretty much every library using throwing PlatformExceptions has it's own set of error codes.

Comment (marandaneto) [reply flutter/lib/src/event_processor/platform_exception_event_processor.dart]: Ok checked internally, and either adding something under `meta` (requires Relay changes) or under `data` would be fine, since PHP already has under `data` and this PR adds under `data`, let's keep it as it is.

**Comment by marandaneto** [comment]
@denrase you need to run `dart format`, and merge it.
