### PR TITLE
Fix: Merge user from scope and event

### LINKED ISSUE #466: sendDefaultPii stops sending of scope.user details
Platform: Dart
SDK: **5.0.0**

---

I tried enabling `SentryOptions.sendDefaultPii` due to the recommendation in the docs and also using `Sentry.configureScope` to set the `user` details.
When sendDefaultPii is enabled the scope.user details are never sent in error reports.

```
Sentry.init(
  (SentryOptions options) async {
    options
      ..dsn = dsn
      ..sendDefaultPii = true;
  },
);
Sentry.configureScope(
  (scope) => scope.user = SentryUser(username: "Tester")
);
```

The cause is [/dart/lib/src/scope.dart#L159 - applyToEvent](https://github.com/getsentry/sentry-dart/blob/main/dart/lib/src/scope.dart#L159) as the user with Pii details have already been created in SentryClient._prepareEvent
```
event = event.copyWith(
...
user: event.user ?? user,
...
);
```

My expectation is that this would have attempted to merge the details, in my case scoped user details would have more precedence.

If this is expected behaviour a note in the docs would have saved a lot of time.

Many thanks!

### PR DESCRIPTION
**Pull request by ueman**
## :scroll: Description
This PR introduces the merge of the user from event and scope.
The user from the event takes precedence over the scope.

## :bulb: Motivation and Context
Fixes https://github.com/getsentry/sentry-dart/issues/466

## :green_heart: How did you test it?
Added a regression test

## :pencil: Checklist

- [x] I reviewed submitted code
- [x] I added tests to verify changes
- [x] I updated the docs if needed
- [x] All tests passing
- [x] No breaking changes

### CODE REVIEW

File: dart/lib/src/scope.dart [hunk 1]
```diff
@@ -213,6 +213,26 @@ class Scope {
...
+    if (eventUser == null && scopeUser != null) {
+      return scopeUser;
+    }
+    // otherwise the user of scope takes precedence over the event user
+    return scopeUser?.copyWith(
+      id: eventUser?.id,
+      email: eventUser?.email,
+      ipAddress: eventUser?.ipAddress,
+      username: eventUser?.username,
+      // TODO should extras be merged?
```
Comment (ueman) [inline dart/lib/src/scope.dart]: I'm not quite sure if the extras of the user should be merged

File: CHANGELOG.md [hunk 2]
```diff
@@ -1,5 +1,7 @@
 # Unreleased
 
+* Fix: Merge user from event and scope
```
Comment (ueman) [inline CHANGELOG.md]:
```suggestion
* Fix: Merge user from event and scope (#467)
```

File: dart/lib/src/scope.dart (hunk 1 above)
Comment (marandaneto) [reply dart/lib/src/scope.dart]: I guess we can do, yes, but event extras keys have precedence

File: dart/lib/src/scope.dart [hunk 3]
```diff
@@ -213,6 +213,26 @@ class Scope {
...
+      extras: eventUser?.extras,
```
Comment (marandaneto) [inline dart/lib/src/scope.dart]: I don't think this would solve the problem, if I understand the code.
if `eventUser?.id` is null and `scopeUser.id` isn't null, the copied user.id will contain a null value.
merging should respect precedence, but if its null, we should use the one that has a value at least.

so I believe we could do something like:
`final id = eventUser?.id ?? scopeUser?.id`
for all properties, and then, create a new user, wdyt?

File: dart/test/scope_test.dart [hunk 4]
```diff
@@ -308,7 +308,10 @@ void main() {
 
       final updatedEvent = await scope.applyToEvent(event, null);
 
-      expect(updatedEvent?.user, eventUser);
+      // We can't check for equality of the user because it
+      // gets merged from event and scope.
+      expect(updatedEvent?.user, isNotNull);
+      expect(updatedEvent?.user?.id, eventUser.id);
```
Comment (marandaneto) [inline dart/test/scope_test.dart]: instead of adding such comment, we could assert field per field, as we know `eventUser` and `scopeUser`, we know what should be the output of each field, or maybe even removing this assert from this test because we have a specific one for the user merging, your call

File: dart/test/sentry_client_test.dart [hunk 5]
```diff
@@ -394,6 +394,25 @@ void main() {
       expect(capturedEvent.fingerprint, eventFingerprint);
       expect(capturedEvent.breadcrumbs, eventCrumbs);
     });
+
+    test('should apply the scope user to null event user fields ', () async {
+      final client = SentryClient(options);
```
Comment (marandaneto) [inline dart/test/sentry_client_test.dart]: great opportunity to create a fixture pattern, lets always do it when we're touching test code and it's not using such a pattern that helps us writing more concise tests, also, reusing code

File: dart/lib/src/scope.dart (hunk 3 above)
Comment (ueman) [reply dart/lib/src/scope.dart]: Using `null` with a `copyWith` keeps the original value because it already does `other ?? this` itself.

Comment (marandaneto) [reply dart/lib/src/scope.dart]: oh yeah, makes sense, my bad

File: dart/test/sentry_client_test.dart [hunk 6]
```diff
@@ -373,6 +374,7 @@ void main() {
     );
 
     setUp(() {
+      fixture = Fixture();
       options = SentryOptions(dsn: fakeDsn);
       options.transport = MockTransport();
       scope = Scope(options)
```
Comment (marandaneto) [inline dart/test/sentry_client_test.dart]: if those things are used across all the tests, they should be part of the fixture too or to be declared within the test if its not the case, the idea of having a fixture is also to encapsulate every property

**Review by marandaneto — APPROVED** [review]
left a suggestion for improving the fixture, but other than that LGTM

File: dart/test/sentry_client_test.dart [hunk 7]
```diff
@@ -352,47 +352,75 @@ void main() {
...
-        ..fingerprint = fingerprint
-        ..addBreadcrumb(crumb);
+      fixture = Fixture();
     });
 
     test('should not apply the scope to non null event fields ', () async {
-      final client = SentryClient(options);
-      await client.captureEvent(event, scope: scope);
+      final transport = MockTransport();
+      final client = fixture.getSut(true, transport);
```
Comment (marandaneto) [inline dart/test/sentry_client_test.dart]:
```suggestion
      final client = fixture.getSut(true, fixture.transport);
```

should not this be part of the fixture?

File: dart/test/sentry_client_test.dart [hunk 8]
```diff
@@ -613,6 +641,38 @@ SentryEvent? eventProcessorDropEvent(SentryEvent event, {dynamic hint}) {
...
+  late SentryEvent event;
+
+  final transaction = '/test/scope';
+  final eventTransaction = '/event/transaction';
+  final fingerprint = ['foo', 'bar', 'baz'];
+  final eventFingerprint = ['123', '456', '798'];
+  final user = SentryUser(id: '123');
+  final eventUser = SentryUser(id: '987');
+  final crumb = Breadcrumb(message: 'bread');
+  final eventCrumbs = [Breadcrumb(message: 'bread')];
```
Comment (marandaneto) [inline dart/test/sentry_client_test.dart]: I dont think this should be part of the fixture declaration, this could be specific per test and values can change, I guess?

File: dart/test/sentry_client_test.dart [hunk 9]
```diff
@@ -613,6 +641,38 @@ SentryEvent? eventProcessorDropEvent(SentryEvent event, {dynamic hint}) {
...
+      level: SentryLevel.warning,
+      transaction: eventTransaction,
+      user: eventUser,
+      fingerprint: eventFingerprint,
+      breadcrumbs: eventCrumbs,
+    );
+  }
+
+  late SentryOptions options;
+  late Scope scope;
```
Comment (marandaneto) [inline dart/test/sentry_client_test.dart]: this sounds more like a createScope(): Scope method than a global field in the fixture

File: dart/test/sentry_client_test.dart (hunk 7 above)
Comment (ueman) [reply dart/test/sentry_client_test.dart]: true

File: dart/test/sentry_client_test.dart (hunk 8 above)
Comment (ueman) [reply dart/test/sentry_client_test.dart]: Those won't change though.

File: dart/test/sentry_client_test.dart [hunk 10]
```diff
@@ -613,11 +638,39 @@ SentryEvent? eventProcessorDropEvent(SentryEvent event, {dynamic hint}) {
...
     return SentryClient(options);
   }
+
+  Scope createScope(SentryOptions options) {
+    return Scope(options)
+      ..user = user
+      ..transaction = transaction
+      ..fingerprint = fingerprint
+      ..addBreadcrumb(crumb);
+  }
```
Comment (marandaneto) [inline dart/test/sentry_client_test.dart]: this should be a method within the `sentry_client_test.dart ` file but not really within the Fixture class

File: dart/test/sentry_client_test.dart [hunk 11]
```diff
@@ -613,11 +638,39 @@ SentryEvent? eventProcessorDropEvent(SentryEvent event, {dynamic hint}) {
...
+  final crumb = Breadcrumb(message: 'bread');
+  final eventCrumbs = [Breadcrumb(message: 'bread')];
+
+  late SentryEvent event = SentryEvent(
+    level: SentryLevel.warning,
+    transaction: eventTransaction,
+    user: eventUser,
+    fingerprint: eventFingerprint,
+    breadcrumbs: eventCrumbs,
+  );
```
Comment (marandaneto) [inline dart/test/sentry_client_test.dart]: similar to https://github.com/getsentry/sentry-dart/pull/467/files#r638548589

File: dart/test/sentry_client_test.dart (hunk 8 above)
Comment (marandaneto) [reply dart/test/sentry_client_test.dart]: still, its not part of the fixture pattern, explained a bit more here https://github.com/getsentry/sentry-dart/pull/467/files#r638550478

File: dart/test/sentry_client_test.dart (hunk 9 above)
Comment (marandaneto) [reply dart/test/sentry_client_test.dart]: https://github.com/getsentry/sentry-dart/pull/467/files#r638548589
