### PR TITLE
Fixes setting the correct locale to contexts with navigatorKey

### LINKED ISSUE #1410: Reported language doesn't always match reality
### Platform

Flutter Mobile

### Obfuscation

Disabled

### Debug Info

Disabled

### Doctor

Unrelated to the Dart/Flutter version

### Version

7.5.0

### Steps to Reproduce

1. Restrict the language manually via the parameters of MaterialApp/CupertinoApp/WidgetsApp as seen in the code snippet. Restrict it to a language different than the device language.
```dart
MaterialApp(
  supportedLocales: supportedLocales,
  locale: selectedLocale,
);
```
2. Cause an error
3. Sentry reports the device language, not the manual set one.

### Expected Result

I would expect the language to be the one set in the MaterialApp.

### Actual Result

Device language is reported.

### Are you willing to submit a PR?

None

### PR DESCRIPTION
**Pull request by buenaflor**
## :scroll: Description
Setting screen locale is not properly reflected in contexts

## :bulb: Motivation and Context

Fixes #1410 

## :green_heart: How did you test it?
Unit test

## :pencil: Checklist

- [x] I reviewed submitted code
- [x] I added tests to verify changes
- [x] No new PII added or SDK only sends newly added PII if `sendDefaultPii` is enabled
- [ ] I updated the docs if needed
- [x] All tests passing
- [x] No breaking changes

## :crystal_ball: Next steps
Add docs

### CODE REVIEW

File: flutter/lib/src/localizations.dart [hunk 1]
```diff
@@ -0,0 +1,13 @@
...
+GlobalKey<NavigatorState> sentryNavigatorKey = GlobalKey<NavigatorState>();
+
+@internal
+Locale? retrieveWidgetLocale() {
+  final BuildContext? context = sentryNavigatorKey.currentContext;
+  if (context != null) {
+    return Localizations.localeOf(context);
+  }
+  return null;
+}
```
Comment (ueman) [inline flutter/lib/src/localizations.dart]: Doesn't it make more sense that this is a property of `SentryFlutterOptions` and user are able to assign it during setup? That way the users are also more flexible, since they can assign their own navigator key.

E.g. something like:
```dart
await SentryFlutter.init((options) {
  options.navigatorKey = userDefinedNavigatorKey;
});
```

The `retrieveWidgetLocale` should also use [`maybeOf`](https://api.flutter.dev/flutter/widgets/Localizations/maybeLocaleOf.html), in order to not throw in case there's no localization set.
```dart
Locale? retrieveWidgetLocale() {
  final BuildContext? context = sentryNavigatorKey.currentContext;
  if (context != null) {
    return Localizations.maybeLocaleOf(context);
  }
  return null;
}
```

Comment (buenaflor) [reply flutter/lib/src/localizations.dart]: Yeah, should be better with a user defined key, thx for the catch

File: flutter/lib/src/sentry_flutter_options.dart [hunk 2]
```diff
@@ -286,4 +286,7 @@ class SentryFlutterOptions extends SentryOptions {
     // ignore: invalid_use_of_internal_member
     super.profilesSampleRate = value;
   }
+
+  /// The navigatorKey used to retrieve the current context of the app.
```
Comment (ueman) [inline flutter/lib/src/sentry_flutter_options.dart]:
```suggestion
  /// The [navigatorKey] is used to add information of the currently used locale to the contexts.
```

File: flutter/lib/src/localizations.dart [hunk 3]
```diff
@@ -0,0 +1,11 @@
...
+import 'package:meta/meta.dart';
+
+@internal
+Locale? retrieveWidgetLocale(GlobalKey<NavigatorState>? navigatorKey) {
+  final BuildContext? context = navigatorKey?.currentContext;
+  if (context != null) {
+    return Localizations.maybeLocaleOf(context);
+  }
+  return null;
+}
```
Comment (ueman) [inline flutter/lib/src/localizations.dart]: I guess this could be added directly in the `FlutterEnricherEventProcessor`, since this is unlikely to be used somewhere else.

**Review by ueman — APPROVED** [review]

**Review by brustolin — APPROVED** [review]
LGTM
