### PR TITLE
fix(logs): Use seconds since the Unix epoch for `log.timestamp`

### LINKED ISSUE #3554: java.lang.NumberFormatException: For input string: "2026-03-12T00:53:38.826549Z"
### Platform

Flutter Mobile Android

### Obfuscation

Enabled

### Debug Info

Enabled

### Doctor

flutter 3.35.6
dependencies:
  sentry_flutter: ^9.14.0
dev_dependencies:
  sentry_dart_plugin: ^3.2.1

### Version

9.14.0

### Steps to Reproduce

``

[sentry] [debug] FramesTrackingIntegration successfully initialized with an expected frame duration of 16ms
[  +26 ms] I/Sentry  (29609): Failed to delete: /data/user/0/com.test.test1/cache/sentry/a5f09e0e3ba1b71e3aed6c735628d5d95ecbaea0/.scope-cache/transaction.json
[        ] W/Sentry  (29609): Current session is not ended, we'd need to end it.
[  +36 ms] D/Sentry  (29609): Serializing object: {
[        ] D/Sentry  (29609): 	"trace_id": "fa7c337a44a84151b95f904b2e2f8701",
[        ] D/Sentry  (29609): 	"span_id": "236b662474e6420a",
[        ] D/Sentry  (29609): 	"op": "default",
[        ] D/Sentry  (29609): 	"origin": "auto",
[        ] D/Sentry  (29609): 	"data": {
[        ] D/Sentry  (29609): 		"thread.name": "main",
[        ] D/Sentry  (29609): 		"thread.id": "29609"
[        ] D/Sentry  (29609): 	}
[        ] D/Sentry  (29609): }
[  +19 ms] D/Sentry  (29609): Serializing object: {
[        ] D/Sentry  (29609): 	"sid": "df4391cd68d84d8ca64ae5b7eb8182fb",
[        ] D/Sentry  (29609): 	"did": "72c2a85e56954b988c205bb0a060da2a",
[        ] D/Sentry  (29609): 	"init": true,
[        ] D/Sentry  (29609): 	"started": "2026-03-12T00:54:46.171Z",
[        ] D/Sentry  (29609): 	"status": "ok",
[        ] D/Sentry  (29609): 	"errors": 0,
[        ] D/Sentry  (29609): 	"timestamp": "2026-03-12T00:54:46.171Z",
[        ] D/Sentry  (29609): 	"attrs": {
[        ] D/Sentry  (29609): 		"release": "com.test.test1@1.0.0+1",
[        ] D/Sentry  (29609): 		"environment": "debug"
[        ] D/Sentry  (29609): 	}
[        ] D/Sentry  (29609): }
[sentry_dart] [debug] MetricsSetup: Metrics configured successfully
[  +38 ms] D/Sentry  (29609): Serializing object: {
[        ] D/Sentry  (29609): 	"timestamp": "2026-03-12T00:54:46.757Z",
[        ] D/Sentry  (29609): 	"type": "system",
[        ] D/Sentry  (29609): 	"data": {
[        ] D/Sentry  (29609): 		"level": 100,
[        ] D/Sentry  (29609): 		"charging": false,
[        ] D/Sentry  (29609): 		"action": "BATTERY_CHANGED"
[        ] D/Sentry  (29609): 	},
[        ] D/Sentry  (29609): 	"category": "device.event",
[        ] D/Sentry  (29609): 	"level": "info"
[        ] D/Sentry  (29609): }
[sentry_dart] [debug] LoggerSetup: Logger configured successfully
[  +40 ms] D/Sentry  (29609): Overwriting session to offline storage: df4391cd68d84d8ca64ae5b7eb8182fb
[  +14 ms] D/Sentry  (29609): Serializing object: {
[        ] D/Sentry  (29609): 	"sid": "df4391cd68d84d8ca64ae5b7eb8182fb",
[        ] D/Sentry  (29609): 	"did": "72c2a85e56954b988c205bb0a060da2a",
[        ] D/Sentry  (29609): 	"init": true,
[        ] D/Sentry  (29609): 	"started": "2026-03-12T00:54:46.171Z",
[        ] D/Sentry  (29609): 	"status": "ok",
[        ] D/Sentry  (29609): 	"errors": 0,
[        ] D/Sentry  (29609): 	"timestamp": "2026-03-12T00:54:46.171Z",
[        ] D/Sentry  (29609): 	"attrs": {
[        ] D/Sentry  (29609): 		"release": "com.test.test1@1.0.0+1",
[        ] D/Sentry  (29609): 		"environment": "debug"
[        ] D/Sentry  (29609): 	}
[        ] D/Sentry  (29609): }
[  +21 ms] D/Sentry  (29609): Adding Envelope to offline storage: /data/user/0/com.test.test1/cache/sentry/a5f09e0e3ba1b71e3aed6c735628d5d95ecbaea0/e51622cdd35a4772836bf8e1bc94f573.envelope
[  +18 ms] D/Sentry  (29609): Envelope flushed
[  +13 ms] W/Sentry  (29609): Cache folder if full (respecting maxSize). Rotating files
[  +20 ms] W/Sentry  (29609): Failed to deserialize object in list.
[        ] W/Sentry  (29609): java.lang.NumberFormatException: For input string: "2026-03-12T00:53:38.826549Z"
[        ] W/Sentry  (29609): 	at jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2054)
[        ] W/Sentry  (29609): 	at jdk.internal.math.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
[        ] W/Sentry  (29609): 	at java.lang.Double.parseDouble(Double.java:662)
[        ] W/Sentry  (29609): 	at io.sentry.vendor.gson.stream.JsonReader.nextDouble(JsonReader.java:916)
[        ] W/Sentry  (29609): 	at io.sentry.JsonObjectReader.nextDoubleOrNull(JsonObjectReader.java:41)
[        ] W/Sentry  (29609): 	at io.sentry.SentryLogEvent$Deserializer.deserialize(SentryLogEvent.java:187)
[        ] W/Sentry  (29609): 	at io.sentry.SentryLogEvent$Deserializer.deserialize(SentryLogEvent.java:161)
[        ] W/Sentry  (29609): 	at io.sentry.JsonObjectReader.nextListOrNull(JsonObjectReader.java:106)
[        ] W/Sentry  (29609): 	at io.sentry.SentryLogEvents$Deserializer.deserialize(SentryLogEvents.java:71)
[        ] W/Sentry  (29609): 	at io.sentry.SentryLogEvents$Deserializer.deserialize(SentryLogEvents.java:57)
[        ] W/Sentry  (29609): 	at io.sentry.JsonSerializer.deserialize(JsonSerializer.java:180)
[        ] W/Sentry  (29609): 	at io.sentry.SentryEnvelopeItem.getLogs(SentryEnvelopeItem.java:157)
[        ] W/Sentry  (29609): 	at io.sentry.clientreport.ClientReportRecorder.recordLostEnvelopeItem(ClientReportRecorder.java:108)
[        ] W/Sentry  (29609): 	at io.sentry.clientreport.ClientReportRecorder.recordLostEnvelope(ClientReportRecorder.java:67)
[        ] W/Sentry  (29609): 	at io.sentry.cache.CacheStrategy.moveInitFlagIfNecessary(CacheStrategy.java:130)
[        ] W/Sentry  (29609): 	at io.sentry.cache.CacheStrategy.rotateCacheIfNeeded(CacheStrategy.java:109)
[        ] W/Sentry  (29609): 	at io.sentry.cache.EnvelopeCache.storeInternal(EnvelopeCache.java:112)
[        ] W/Sentry  (29609): 	at io.sentry.cache.EnvelopeCache.storeEnvelope(EnvelopeCache.java:106)
[        ] W/Sentry  (29609): 	at io.sentry.android.core.cache.AndroidEnvelopeCache.storeInternalAndroid(AndroidEnvelopeCache.java:67)
[        ] W/Sentry  (29609): 	at io.sentry.android.core.cache.AndroidEnvelopeCache.storeEnvelope(AndroidEnvelopeCache.java:63)
[        ] W/Sentry  (29609): 	at io.sentry.transport.AsyncHttpTransport$EnvelopeSender.flush(AsyncHttpTransport.java:274)
[        ] W/Sentry  (29609): 	at io.sentry.transport.AsyncHttpTransport$EnvelopeSender.run(AsyncHttpTransport.java:247)
[        ] W/Sentry  (29609): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:524)
[        ] W/Sentry  (29609): 	at java.util.concurrent.FutureTask.run(FutureTask.java:317)
[        ] W/Sentry  (29609): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1156)
[        ] W/Sentry  (29609): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:651)
[        ] W/Sentry  (29609): 	at java.lang.Thread.run(Thread.java:1119)
[  +15 ms] E/Sentry  (29609): Error when deserializing
[        ] E/Sentry  (29609): java.lang.IllegalStateException: Expected END_ARRAY but was STRING at line 1 column 53 path $.items[0].timestamp
[        ] E/Sentry  (29609): 	at io.sentry.vendor.gson.stream.JsonReader.endArray(JsonReader.java:375)
[        ] E/Sentry  (29609): 	at io.sentry.JsonObjectReader.nextListOrNull(JsonObjectReader.java:112)
[        ] E/Sentry  (29609): 	at io.sentry.SentryLogEvents$Deserializer.deserialize(SentryLogEvents.java:71)
[        ] E/Sentry  (29609): 	at io.sentry.SentryLogEvents$Deserializer.deserialize(SentryLogEvents.java:57)
[        ] E/Sentry  (29609): 	at io.sentry.JsonSerializer.deserialize(JsonSerializer.java:180)
[        ] E/Sentry  (29609): 	at io.sentry.SentryEnvelopeItem.getLogs(SentryEnvelopeItem.java:157)
[        ] E/Sentry  (29609): 	at io.sentry.clientreport.ClientReportRecorder.recordLostEnvelopeItem(ClientReportRecorder.java:108)
[        ] E/Sentry  (29609): 	at io.sentry.clientreport.ClientReportRecorder.recordLostEnvelope(ClientReportRecorder.java:67)
[        ] E/Sentry  (29609): 	at io.sentry.cache.CacheStrategy.moveInitFlagIfNecessary(CacheStrategy.java:130)
[        ] E/Sentry  (29609): 	at io.sentry.cache.CacheStrategy.rotateCacheIfNeeded(CacheStrategy.java:109)
[        ] E/Sentry  (29609): 	at io.sentry.cache.EnvelopeCache.storeInternal(EnvelopeCache.java:112)
[        ] E/Sentry  (29609): 	at io.sentry.cache.EnvelopeCache.storeEnvelope(EnvelopeCache.java:106)
[        ] E/Sentry  (29609): 	at io.sentry.android.core.cache.AndroidEnvelopeCache.storeInternalAndroid(AndroidEnvelopeCache.java:67)
[        ] E/Sentry  (29609): 	at io.sentry.android.core.cache.AndroidEnvelopeCache.storeEnvelope(AndroidEnvelopeCache.java:63)
[        ] E/Sentry  (29609): 	at io.sentry.transport.AsyncHttpTransport$EnvelopeSender.flush(AsyncHttpTransport.java:274)
[        ] E/Sentry  (29609): 	at io.sentry.transport.AsyncHttpTransport$EnvelopeSender.run(AsyncHttpTransport.java:247)
[        ] E/Sentry  (29609): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:524)
[        ] E/Sentry  (29609): 	at java.util.concurrent.FutureTask.run(FutureTask.java:317)
[        ] E/Sentry  (29609): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1156)
[        ] E/Sentry  (29609): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:651)
[        ] E/Sentry  (29609): 	at java.lang.Thread.run(Thread.java:1119)
[  +22 ms] D/Sentry  (29609): Unable to parse lost logs envelope item.
[        ] D/Sentry  (29609): Adding Envelope to offline storage: /data/user/0/com.test.test1/cache/sentry/a5f09e0e3ba1b71e3aed6c735628d5d95ecbaea0/1b27f52e4ef2486fa6594a43bbfb8c2c.envelope
[  +41 ms] D/Sentry  (29609): Serializing object: {
[        ] D/Sentry  (29609): 	"sid": "9f49d9362e2c4a9caa67d4f82c5db396",
[        ] D/Sentry  (29609): 	"did": "72c2a85e56954b988c205bb0a060da2a",
[        ] D/Sentry  (29609): 	"started": "2026-03-12T00:53:22.392Z",
[        ] D/Sentry  (29609): 	"status": "exited",
[        ] D/Sentry  (29609): 	"seq": 1773276887038,
[        ] D/Sentry  (29609): 	"errors": 0,
[        ] D/Sentry  (29609): 	"duration": 84.646,
[        ] D/Sentry  (29609): 	"timestamp": "2026-03-12T00:54:47.038Z",
[        ] D/Sentry  (29609): 	"attrs": {
[        ] D/Sentry  (29609): 		"release": "com.test.test1@1.0.0+1",
[        ] D/Sentry  (29609): 		"environment": "debug"
[        ] D/Sentry  (29609): 	}
[        ] D/Sentry  (29609): }
[  +21 ms] D/Sentry  (29609): Envelope flushed
[  +16 ms] I/Choreographer(29609): Skipped 169 frames!  The application may be doing too much work on its main thread.
[+1509 ms] D/Sentry  (29609): Serializing object: {
[  +13 ms] D/Sentry  (29609): 	"timestamp": "2026-03-12T00:54:48.777Z",
[        ] D/Sentry  (29609): 	"type": "navigation",
[        ] D/Sentry  (29609): 	"data": {
[        ] D/Sentry  (29609): 		"state": "didPush",
[        ] D/Sentry  (29609): 		"to": "/"
[        ] D/Sentry  (29609): 	},
[        ] D/Sentry  (29609): 	"category": "navigation",
[        ] D/Sentry  (29609): 	"level": "info"
[        ] D/Sentry  (29609): }
[+1187 ms] I/Choreographer(29609): Skipped 160 frames!  The application may be doing too much work on its main thread.
[{"id":0,"result":{"value":"android","type":"_extensionType","method":"ext.flutter.platformOverride"}}]
[{"id":1,"result":{"timeDilation":"1.0","type":"_extensionType","method":"ext.flutter.timeDilation"}}]
[{"id":2,"result":{"enabled":"false","type":"_extensionType","method":"ext.flutter.debugPaint"}}]
[{"id":3,"result":{"enabled":"false","type":"_extensionType","method":"ext.flutter.debugPaintBaselinesEnabled"}}]
[{"id":4,"result":{"enabled":"false","type":"_extensionType","method":"ext.flutter.repaintRainbow"}}]
[{"id":5,"result":{"enabled":"false","type":"_extensionType","method":"ext.flutter.showPerformanceOverlay"}}]
[{"id":6,"result":{"enabled":"true","type":"_extensionType","method":"ext.flutter.debugAllowBanner"}}]
[{"id":7,"result":{"enabled":"true","type":"_extensionType","method":"ext.flutter.inspector.structuredErrors"}}]
[{"id":8,"result":{"enabled":"false","type":"_extensionType","method":"ext.flutter.inspector.show"}}]
[{"id":9,"result":{"enabled":"false","type":"_extensionType","method":"ext.flutter.inspector.trackRebuildDirtyWidgets"}}]
[{"id":10,"result":{"enabled":"false","type":"_extensionType","method":"ext.flutter.inspector.trackRepaintWidgets"}}]
[{"id":11,"result":{"enabled":"true","type":"_extensionType","method":"ext.flutter.inspector.structuredErrors"}}]
[+1339 ms] D/SplashScreenView(29609): Building from parcel drawable: android.graphics.drawable.BitmapDrawable@c61c820
[  +51 ms] D/SplashScreenView(29609): Build android.window.SplashScreenView{e9a6b9e V.E...... ......ID 0,0-0,0}
[        ] D/SplashScreenView(29609): Icon: view: android.widget.ImageView{ebe267f V.ED..... ......I. 0,0-0,0 #1020542 android:id/splashscreen_icon_view} drawable: android.graphics.drawable.BitmapDrawable@c61c820 size: 576
[        ] D/SplashScreenView(29609): Branding: view: android.view.View{beb464c V.ED..... ......I. 0,0-0,0 #1020541 android:id/splashscreen_branding_view} drawable: android.graphics.drawable.BitmapDrawable@d604695 size w: 600 h: 240
[ +319 ms] D/InsetsController(29609): hide(ime(), fromIme=false)
[  +28 ms] I/ImeTracker(29609): com.test.test1:87d02a76: onCancelled at PHASE_CLIENT_ALREADY_HIDDEN
[ +208 ms] D/SplashScreenView(29609): remove starting view
[+1715 ms] D/Sentry  (29609): Serializing object: {}
[ +571 ms] W/Sentry  (29609): Cache folder if full (respecting maxSize). Rotating files
[  +13 ms] W/Sentry  (29609): Failed to deserialize object in list.
[        ] W/Sentry  (29609): java.lang.NumberFormatException: For input string: "2026-03-12T00:53:45.117135Z"
[        ] W/Sentry  (29609): 	at jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2054)
[        ] W/Sentry  (29609): 	at jdk.internal.math.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
[        ] W/Sentry  (29609): 	at java.lang.Double.parseDouble(Double.java:662)
[        ] W/Sentry  (29609): 	at io.sentry.vendor.gson.stream.JsonReader.nextDouble(JsonReader.java:916)
[        ] W/Sentry  (29609): 	at io.sentry.JsonObjectReader.nextDoubleOrNull(JsonObjectReader.java:41)
[        ] W/Sentry  (29609): 	at io.sentry.SentryLogEvent$Deserializer.deserialize(SentryLogEvent.java:187)
[        ] W/Sentry  (29609): 	at io.sentry.SentryLogEvent$Deserializer.deserialize(SentryLogEvent.java:161)
[        ] W/Sentry  (29609): 	at io.sentry.JsonObjectReader.nextListOrNull(JsonObjectReader.java:106)
[        ] W/Sentry  (29609): 	at io.sentry.SentryLogEvents$Deserializer.deserialize(SentryLogEvents.java:71)
[        ] W/Sentry  (29609): 	at io.sentry.SentryLogEvents$Deserializer.deserialize(SentryLogEvents.java:57)
[        ] W/Sentry  (29609): 	at io.sentry.JsonSerializer.deserialize(JsonSerializer.java:180)
[        ] W/Sentry  (29609): 	at io.sentry.SentryEnvelopeItem.getLogs(SentryEnvelopeItem.java:157)
[        ] W/Sentry  (29609): 	at io.sentry.clientreport.ClientReportRecorder.recordLostEnvelopeItem(ClientReportRecorder.java:108)
[        ] W/Sentry  (29609): 	at io.sentry.clientreport.ClientReportRecorder.recordLostEnvelope(ClientReportRecorder.java:67)
[        ] W/Sentry  (29609): 	at io.sentry.cache.CacheStrategy.moveInitFlagIfNecessary(CacheStrategy.java:130)
[        ] W/Sentry  (29609): 	at io.sentry.cache.CacheStrategy.rotateCacheIfNeeded(CacheStrategy.java:109)
[        ] W/Sentry  (29609): 	at io.sentry.cache.EnvelopeCache.storeInternal(EnvelopeCache.java:112)
[        ] W/Sentry  (29609): 	at io.sentry.cache.EnvelopeCache.storeEnvelope(EnvelopeCache.java:106)
[        ] W/Sentry  (29609): 	at io.sentry.android.core.cache.AndroidEnvelopeCache.storeInternalAndroid(AndroidEnvelopeCache.java:67)
[        ] W/Sentry  (29609): 	at io.sentry.android.core.cache.AndroidEnvelopeCache.storeEnvelope(AndroidEnvelopeCache.java:63)
[        ] W/Sentry  (29609): 	at io.sentry.transport.AsyncHttpTransport$EnvelopeSender.flush(AsyncHttpTransport.java:274)
[        ] W/Sentry  (29609): 	at io.sentry.transport.AsyncHttpTransport$EnvelopeSender.run(AsyncHttpTransport.java:247)
[        ] W/Sentry  (29609): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:524)
[        ] W/Sentry  (29609): 	at java.util.concurrent.FutureTask.run(FutureTask.java:317)
[        ] W/Sentry  (29609): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1156)
[        ] W/Sentry  (29609): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:651)
[        ] W/Sentry  (29609): 	at java.lang.Thread.run(Thread.java:1119)
[   +6 ms] E/Sentry  (29609): Error when deserializing
[        ] E/Sentry  (29609): java.lang.IllegalStateException: Expected END_ARRAY but was STRING at line 1 column 53 path $.items[0].timestamp
[        ] E/Sentry  (29609): 	at io.sentry.vendor.gson.stream.JsonReader.endArray(JsonReader.java:375)
[        ] E/Sentry  (29609): 	at io.sentry.JsonObjectReader.nextListOrNull(JsonObjectReader.java:112)
[        ] E/Sentry  (29609): 	at io.sentry.SentryLogEvents$Deserializer.deserialize(SentryLogEvents.java:71)
[        ] E/Sentry  (29609): 	at io.sentry.SentryLogEvents$Deserializer.deserialize(SentryLogEvents.java:57)
[        ] E/Sentry  (29609): 	at io.sentry.JsonSerializer.deserialize(JsonSerializer.java:180)
[        ] E/Sentry  (29609): 	at io.sentry.SentryEnvelopeItem.getLogs(SentryEnvelopeItem.java:157)
[        ] E/Sentry  (29609): 	at io.sentry.clientreport.ClientReportRecorder.recordLostEnvelopeItem(ClientReportRecorder.java:108)
[        ] E/Sentry  (29609): 	at io.sentry.clientreport.ClientReportRecorder.recordLostEnvelope(ClientReportRecorder.java:67)
[        ] E/Sentry  (29609): 	at io.sentry.cache.CacheStrategy.moveInitFlagIfNecessary(CacheStrategy.java:130)
[        ] E/Sentry  (29609): 	at io.sentry.cache.CacheStrategy.rotateCacheIfNeeded(CacheStrategy.java:109)
[        ] E/Sentry  (29609): 	at io.sentry.cache.EnvelopeCache.storeInternal(EnvelopeCache.java:112)
[        ] E/Sentry  (29609): 	at io.sentry.cache.EnvelopeCache.storeEnvelope(EnvelopeCache.java:106)
[        ] E/Sentry  (29609): 	at io.sentry.android.core.cache.AndroidEnvelopeCache.storeInternalAndroid(AndroidEnvelopeCache.java:67)
[        ] E/Sentry  (29609): 	at io.sentry.android.core.cache.AndroidEnvelopeCache.storeEnvelope(AndroidEnvelopeCache.java:63)
[        ] E/Sentry  (29609): 	at io.sentry.transport.AsyncHttpTransport$EnvelopeSender.flush(AsyncHttpTransport.java:274)
[        ] E/Sentry  (29609): 	at io.sentry.transport.AsyncHttpTransport$EnvelopeSender.run(AsyncHttpTransport.java:247)
[        ] E/Sentry  (29609): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:524)
[        ] E/Sentry  (29609): 	at java.util.concurrent.FutureTask.run(FutureTask.java:317)
[        ] E/Sentry  (29609): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1156)
[        ] E/Sentry  (29609): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:651)
[        ] E/Sentry  (29609): 	at java.lang.Thread.run(Thread.java:1119)
[  +10 ms] D/Sentry  (29609): Unable to parse lost logs envelope item.
[        ] D/Sentry  (29609): Adding Envelope to offline storage: /data/user/0/com.test.test1/cache/sentry/a5f09e0e3ba1b71e3aed6c735628d5d95ecbaea0/5ee28096838d4babb26760e00e6b1831.envelope
[   +3 ms] D/Sentry  (29609): Envelope flushed

``
import 'dart:async';
import 'dart:convert';

import 'package:flutter/material.dart';
import 'package:sentry_flutter/sentry_flutter.dart';

const String exampleDsn =
    'https://xx@xx.ingest.us.sentry.io/xxx';

final GlobalKey<NavigatorState> navigatorKey = GlobalKey<NavigatorState>();

Future<void> main() async {
  await setupSentry(
        () => runApp(
      SentryWidget(
        child: DefaultAssetBundle(
          bundle: SentryAssetBundle(),
          child: const MyApp(),
        ),
      ),
    ),
    exampleDsn,
  );
}

Future<void> setupSentryWithCustomInit(
    AppRunner appRunner,
    OptionsConfiguration optionsConfiguration,
    ) async {
  return SentryFlutter.init(optionsConfiguration, appRunner: appRunner);
}

Future<void> setupSentry(AppRunner appRunner, String dsn) async {
  await SentryFlutter.init((options) {
    options.dsn = exampleDsn;
    options.tracesSampleRate = 1.0;
    options.profilesSampleRate = 1.0;
    options.attachThreads = true;
    options.sendDefaultPii = true;
    options.reportSilentFlutterErrors = true;
    options.diagnosticLevel = SentryLevel.debug;
    options.debug = true;
    options.enableLogs = true;
    options.connectionTimeout = const Duration(seconds: 15);
    options.readTimeout = const Duration(seconds: 15);
    options.maxCacheItems = 3;
  }, appRunner: appRunner);
}

class MyApp extends StatefulWidget {
  const MyApp({super.key});

  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  void initState() {
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      navigatorKey: navigatorKey,
      navigatorObservers: [SentryNavigatorObserver()],
      theme: ThemeData.light(),
      home: Scaffold(
        body: Center(
          child: ElevatedButton(
            onPressed: () async {
              if (context.mounted) {
                Sentry.logger.fmt.info("%s added %s to cart.", ["John", "Product 1"]);
              }
            },
            child: const Text('Test'),
          ),
        ),
      ),
    );
  }
}
\
``

### Expected Result

send data to sentry server

### Actual Result

send data to sentry server fail

### Are you willing to submit a PR?

None

### PR DESCRIPTION
**Pull request by denrase**
## :scroll: Description

We have incorrectly used `timestamp.toIso8601String()` and this was only accepted because the backend does lenient date/timestamp parsing.

On the native Android SDK it does lead to parsing issues though, as reported by a user.

## :bulb: Motivation and Context

Closes #3554

## :green_heart: How did you test it?

Unit tests. Sample app log Android app.

## :pencil: Checklist

- [x] I reviewed submitted code
- [x] I added tests to verify changes
- [x] No new PII added or SDK only sends newly added PII if `sendDefaultPii` is enabled
- [x] I updated the docs if needed
- [x] All tests passing
- [x] No breaking changes

### CODE REVIEW

File: packages/dart/lib/src/telemetry/log/log.dart [hunk 1]
```diff
@@ -27,7 +27,7 @@ class SentryLog {
 
   Map<String, dynamic> toJson() {
     return {
-      'timestamp': timestamp.toIso8601String(),
+      'timestamp': timestamp.microsecondsSinceEpoch / 1000000.0,
```
Comment (buenaflor) [inline packages/dart/lib/src/telemetry/log/log.dart]: since we need this for spans and metrics as well let's create a shared utility.

metrics uses `timestamp.millisecondsSinceEpoch / 1000.0` but using microseconds is preferred here 

you can also update the metrics impl

I'd suggest this:

```dart
extension DateTimeExtension on DateTime {
  double get secondsSinceEpoch => microsecondsSinceEpoch / 1000000.0;
}
```

**Review by buenaflor — CHANGES_REQUESTED** [review]
some parts aren't using the new extension function

**Review by buenaflor — APPROVED** [review]
LGTM!
