### PR TITLE
TTID/TTFD Improvements

### LINKED ISSUE #2852: TTFD improvements
### Description

- starting and finishing spans happen simultaenously, we’re not awaiting the span before to finish -> this is already a major issue in consistency
- `Sentry.reportFullyDisplayed might finish the wrong TTFD span`
  - Screen A starts TTFD and wants to finish it in the background after 5 seconds
  - Within those 5 seconds a user navigates to Screen B, Screen B starts TTFD span and replaces the TTFD span from A because they are global
  - Since the background work is still running the TTFD from Screen A is finished and reported as TTFD for Screen B which is false reporting

### PR DESCRIPTION
**Pull request by denrase**
## :scroll: Description

- Adds a `SentryDisplay` with `reportFullyDisplayed`, fixing #2852
- Adds `SentryDisplayWidget` to wrap `SentryDisplay`
- Refactoring
  - Remove global singleton instances for TTID/TTFD trackers
  - Remove redundant startTimestamp
  - Inject options in TTFD tracker instead of using static
 - Fixes an issue where root screen ttfd could not be reported
 
## :bulb: Motivation and Context

Closes #2852

## :green_heart: How did you test it?

Unit tests

## :pencil: Checklist

- [x] I reviewed submitted code
- [x] I added tests to verify changes
- [ ] No new PII added or SDK only sends newly added PII if `sendDefaultPii` is enabled
- [ ] I updated the docs if needed
- [x] All tests passing
- [x] No breaking changes

### CODE REVIEW

**Review by buenaflor — COMMENTED** [review]
I believe there's still the issue of the async calls not being awaited - finish and start time to display in didPush

**Comment by buenaflor** [comment]
as discussed let's find a more user friendly way to solve this. perhaps through a widget

**Comment by buenaflor** [comment]
As discussed let's try to use the spanId similar to react native

File: flutter/lib/src/navigation/time_to_display_tracker.dart [hunk 1]
```diff
@@ -8,44 +8,49 @@ import 'time_to_initial_display_tracker.dart';
...
-        transaction: transaction,
-        startTimestamp: startTimestamp,
-      );
+      await _ttfdTracker.track(transaction: transaction);
     }
   }
 
   @internal
-  Future<void> reportFullyDisplayed() async {
+  Future<void> reportFullyDisplayed({SpanId? spanId}) async {
```
Comment (buenaflor) [inline flutter/lib/src/navigation/time_to_display_tracker.dart]: is this nullable for backwards compatibility?

File: flutter/lib/src/navigation/time_to_full_display_tracker.dart [hunk 2]
```diff
@@ -59,7 +45,13 @@ class TimeToFullDisplayTracker {
...
   }
 
-  Future<void> reportFullyDisplayed() async {
+  Future<void> reportFullyDisplayed({SpanId? spanId}) async {
+    final startSpanId = _transaction?.context.spanId;
+    final endSpanId = spanId;
+
+    if (startSpanId != null && endSpanId != null && startSpanId != endSpanId) {
+      return;
+    }
```
Comment (buenaflor) [inline flutter/lib/src/navigation/time_to_full_display_tracker.dart]: I believe in this case we can finish the TTFD span with `SpanStatus.DEADLINE_EXCEEDED` and match the time to TTID endtime

File: flutter/lib/src/navigation/time_to_full_display_tracker.dart [hunk 3]
```diff
@@ -69,14 +61,10 @@ class TimeToFullDisplayTracker {
...
 
-    if (ttfdSpan == null ||
-        ttfdSpan.finished ||
-        startTimestamp == null ||
-        endTimestamp == null) {
-      options.logger(
+    if (ttfdSpan == null || ttfdSpan.finished || endTimestamp == null) {
+      _options.logger(
         SentryLevel.warning,
         'TTFD tracker not started or already completed. Dropping TTFD measurement.',
```
Comment (buenaflor) [inline flutter/lib/src/navigation/time_to_full_display_tracker.dart]: Not part of this PR but I've seen this many times throughout debugging

imo we should lower the log level. maybe to `debug`

File: flutter/lib/src/sentry_flutter.dart [hunk 4]
```diff
@@ -244,13 +244,15 @@ mixin SentryFlutter {
     options.sdk = sdk;
   }
 
-  /// Reports the time it took for the screen to be fully displayed.
-  /// This requires the [SentryFlutterOptions.enableTimeToFullDisplayTracing] option to be set to `true`.
+  @Deprecated('Use SentryDisplay.reportFullyDisplayed() instead.')
```
Comment (buenaflor) [inline flutter/lib/src/sentry_flutter.dart]:
```suggestion
  @Deprecated('Use reportFullyDisplayed() on a SentryDisplay instance instead. Read the TTFD documentation at https://docs.sentry.io/platforms/dart/guides/flutter/integrations/routing-instrumentation/#time-to-full-display.')
```

File: flutter/lib/src/navigation/sentry_display_widget.dart [hunk 5]
```diff
@@ -0,0 +1,115 @@
...
+
+  @override
+  Widget build(BuildContext context) {
+    return _SentryDisplayInheritedWidget(
+      state: this,
+      child: widget.child,
+    );
+  }
+
+  void reportFullyDisplayed() {
```
Comment (buenaflor) [inline flutter/lib/src/navigation/sentry_display_widget.dart]:
```suggestion
  Future<void> reportFullyDisplayed() {
```

**Review by buenaflor — COMMENTED** [review]
I like the approach manual and widget approach!

let's try and figure out how to handle the root transactions.

maybe it makes sense to have a central place where the navigator and the app start fetches the transaction from

File: flutter/lib/src/navigation/sentry_display.dart [hunk 6]
```diff
@@ -0,0 +1,27 @@
...
+          spanId: spanId,
+        );
+      } catch (exception, stackTrace) {
+        options.logger(
+          SentryLevel.error,
+          'Error while reporting TTFD',
+          exception: exception,
+          stackTrace: stackTrace,
+        );
+      }
```
Comment (buenaflor) [inline flutter/lib/src/navigation/sentry_display.dart]:
```suggestion
      } catch (exception, stackTrace) {
        if (options.automatedTestMode) {
          rethrow;
        }
        options.logger(
          SentryLevel.error,
          'Error while reporting TTFD',
          exception: exception,
          stackTrace: stackTrace,
        );
      }
```

File: flutter/lib/src/navigation/sentry_display.dart [hunk 7]
```diff
@@ -0,0 +1,27 @@
...
+class SentryDisplay {
+  final Hub _hub;
+  final SpanId spanId;
+
+  SentryDisplay(this.spanId, {Hub? hub}) : _hub = hub ?? HubAdapter();
+
+  Future<void> reportFullyDisplayed() async {
+    // ignore: invalid_use_of_internal_member
+    final options = _hub.options;
+    if (options is SentryFlutterOptions) {
```
Comment (buenaflor) [inline flutter/lib/src/navigation/sentry_display.dart]: I guess we can return early here so we have one less nesting of if

File: flutter/lib/src/navigation/time_to_display_tracker.dart (hunk 1 above)
Comment (denrase) [reply flutter/lib/src/navigation/time_to_display_tracker.dart]: That was the intent, yes. But i'll check what it would mean if we change this here, since it's internal API.

File: flutter/lib/src/navigation/time_to_initial_display_tracker.dart [hunk 8]
```diff
@@ -11,101 +11,76 @@ import '../frame_callback_handler.dart';
...
-
     final ttidSpan = transaction.startChild(
       SentrySpanOperations.uiTimeToInitialDisplay,
       description: '${transaction.name} initial display',
-      startTimestamp: startTimestamp,
+      startTimestamp: transaction.startTimestamp,
     );
+    ttidSpan.origin = SentryTraceOrigins.autoUiTimeToDisplay;
+
+    final determinedEndTimestamp = await _determineEndTime(endTimestamp);
```
Comment (buenaflor) [inline flutter/lib/src/navigation/time_to_initial_display_tracker.dart]: do we need to pass the endTimestamp?

All we do in the function is check if it is not null and return it again 

```dart
final determinedEndTimestamp = endTimestamp ?? await _determineEndTime();
```

File: flutter/lib/src/navigation/time_to_display_tracker.dart [hunk 9]
```diff
@@ -1,52 +1,84 @@
...
     if (options.enableTimeToFullDisplayTracing) {
-      return _ttfdTracker.reportFullyDisplayed();
+      return _ttfdTracker.reportFullyDisplayed(spanId: spanId);
+    }
+  }
+
+  // Cancel unfinished TTID/TTFD spans, e.g this might happen if the user navigates
+  // away from the current route before TTFD or TTID is finished.
+  @internal
```
Comment (buenaflor) [inline flutter/lib/src/navigation/time_to_display_tracker.dart]: if we mark the class `@internal` do we need to mark all the functions internal as well? maybe we don't need to

File: flutter/lib/src/navigation/time_to_display_tracker.dart [hunk 10]
```diff
@@ -1,52 +1,84 @@
...
 import 'time_to_full_display_tracker.dart';
 import 'time_to_initial_display_tracker.dart';
+// ignore: implementation_imports
+import 'package:sentry/src/sentry_tracer.dart';
 
 @internal
 class TimeToDisplayTracker {
   final TimeToInitialDisplayTracker _ttidTracker;
   final TimeToFullDisplayTracker _ttfdTracker;
+
```
Comment (buenaflor) [inline flutter/lib/src/navigation/time_to_display_tracker.dart]:
```suggestion
```

File: flutter/lib/src/integrations/native_app_start_integration.dart [hunk 11]
```diff
@@ -17,6 +17,14 @@ class NativeAppStartIntegration extends Integration<SentryFlutterOptions> {
 
   @override
   void call(Hub hub, SentryFlutterOptions options) async {
+    final context = SentryTransactionContext(
+      'root /',
+      // ignore: invalid_use_of_internal_member
+      SentrySpanOperations.uiLoad,
+    );
+    options.timeToDisplayTracker.transactionId = context.spanId;
+    options.timeToDisplayTracker.rootTransactionId = context.spanId;
```
Comment (buenaflor) [inline flutter/lib/src/integrations/native_app_start_integration.dart]: we could add a quick comment why we create the context here early

File: flutter/lib/src/navigation/time_to_full_display_tracker.dart (hunk 2 above)
Comment (denrase) [reply flutter/lib/src/navigation/time_to_full_display_tracker.dart]: We don't know if the user might call with the correct id at a later time.

File: flutter/lib/src/navigation/time_to_display_tracker.dart (hunk 9 above)
Comment (denrase) [reply flutter/lib/src/navigation/time_to_display_tracker.dart]: None of the methods are API users are supposed to call in isolation. Think the whole class as @internal is warranted here.

File: flutter/lib/src/integrations/native_app_start_handler.dart [hunk 12]
```diff
@@ -48,11 +51,23 @@ class NativeAppStartHandler {
...
+          options.timeToDisplayTracker.rootTransactionEndTimestamp;
+      if (reportedRootTTFDEndTimestamp != null) {
+        options.timeToDisplayTracker.reportFullyDisplayed(
+          spanId: rootScreenTransaction.context.spanId,
+          endTimestamp: reportedRootTTFDEndTimestamp.isAfter(appStartInfo.end)
+              ? reportedRootTTFDEndTimestamp
+              : appStartInfo.end,
+        );
+      }
+    });
```
Comment (buenaflor) [inline flutter/lib/src/integrations/native_app_start_handler.dart]: why do we need the 1ms delay?

File: flutter/lib/src/navigation/time_to_display_tracker.dart (hunk 9 above)
Comment (buenaflor) [reply flutter/lib/src/navigation/time_to_display_tracker.dart]: yeah the whole class as @internal is fine, what I mean is whether we need to mark all the functions as well or if we can omit them for the functions

File: flutter/lib/src/integrations/native_app_start_handler.dart (hunk 12 above)
Comment (denrase) [reply flutter/lib/src/integrations/native_app_start_handler.dart]: just a small delay, just so it is called after the `track` call, where we are awaiting ttfd

Comment (ueman) [reply flutter/lib/src/integrations/native_app_start_handler.dart]: Can't you use a `Future.microtask` here? It's guaranteed to be run in order, but you don't need the delay.

File: flutter/lib/src/navigation/sentry_display_widget.dart [hunk 13]
```diff
@@ -0,0 +1,115 @@
...
+        .dependOnInheritedWidgetOfExactType<_SentryDisplayInheritedWidget>()!
+        .state;
+  }
+
+  @override
+  State<SentryDisplayWidget> createState() => _SentryDisplayWidgetState();
+}
+
+class _SentryDisplayWidgetState extends State<SentryDisplayWidget> {
+  SentryDisplay? _display;
```
Comment (ueman) [inline flutter/lib/src/navigation/sentry_display_widget.dart:86]:
```suggestion
  late final SentryDisplay _display = SentryFlutter.currentDisplay();
```

This way you don't need the initState()

File: flutter/lib/src/integrations/native_app_start_handler.dart (hunk 12 above)
Comment (denrase) [reply flutter/lib/src/integrations/native_app_start_handler.dart]: `Future.microtask` did not work, but i made this even simpler and more robust. If we know the ttfd at this point, we just inject it into the track method.

**Review by buenaflor — COMMENTED** [review]
Looks good so far, I'll do another in-depth pass later.

File: flutter/example/lib/main.dart [hunk 14]
```diff
@@ -62,7 +62,7 @@ Future<void> setupSentry(
   BeforeSendCallback? beforeSendCallback,
 }) async {
   await SentryFlutter.init(
-    (options) {
+    (options) async {
```
Comment (buenaflor) [inline flutter/example/lib/main.dart]: do we need this async?

File: CHANGELOG.md [hunk 15]
```diff
@@ -2,6 +2,13 @@
 
 ## Unreleased
 
+- TTID/TTFD Improvements ([#2866](https://github.com/getsentry/sentry-dart/pull/2866))
+```dart
+final sentryDisplay = Sentry.currentDisplay();
+// Do some work....
+sentryDisplay?.reportFullyDisplayed()
+```
```
Comment (buenaflor) [inline CHANGELOG.md]: let's be a bit more specific on how to the new API works and also pls describe the widget

File: flutter/lib/src/navigation/sentry_navigator_observer.dart [hunk 16]
```diff
@@ -364,33 +332,32 @@ class SentryNavigatorObserver extends RouteObserver<PageRoute<dynamic>> {
...
   }
 
   Future<void> _startTimeToDisplayTracking(
       Route<dynamic>? route, DateTime startTimestamp) async {
     try {
       final routeName = _getRouteName(route) ?? _currentRouteName;
-      if (!_enableAutoTransactions || routeName == null) {
+      final isRoot = routeName == '/';
+      if (!_enableAutoTransactions || routeName == null || isRoot) {
         return;
```
Comment (buenaflor) [inline flutter/lib/src/navigation/sentry_navigator_observer.dart]: let's add a small comment why we dont continue here if it's root

File: CHANGELOG.md [hunk 17]
```diff
@@ -1,5 +1,30 @@
...
+## Unreleased
+
+### Features
+
+- TTID/TTFD Improvements ([#2866](https://github.com/getsentry/sentry-dart/pull/2866))
+```dart
+// To report TTFD you need to use the SentryNavigatorObserver.
+ 
+// Before reporting long running work, you can get a refernce to the currently displayed route.
+final sentryDisplay = Sentry.currentDisplay();
```
Comment (buenaflor) [inline CHANGELOG.md]:
```suggestion
// Before reporting long running work, you can get a reference to the currently displayed route.
final sentryDisplay = Sentry.currentDisplay();
```

pls explain that it has to be in a stateful widget within initState or if they use a stateless they should use the display widget instead

File: CHANGELOG.md [hunk 18]
```diff
@@ -1,5 +1,30 @@
...
+
+// Then do some work like file I/O or networking....
+
+// Finally call `reportFullyDisplayed` on the sentryDisplay instance.
```
Comment (buenaflor) [inline CHANGELOG.md]:
```suggestion
// Finally call `reportFullyDisplayed` on the sentryDisplay instance when the work operation is done.
```

File: CHANGELOG.md [hunk 19]
```diff
@@ -1,5 +1,30 @@
...
+sentryDisplay?.reportFullyDisplayed()
+
+// Alternativlye, you can wrap your widget in `SentryDisplayWidget`.
```
Comment (buenaflor) [inline CHANGELOG.md]:
```suggestion
// Alternatively, you can wrap your widget in `SentryDisplayWidget`.
```

File: CHANGELOG.md [hunk 20]
```diff
@@ -1,5 +1,30 @@
...
+
+SentryDisplayWidget(child: YourWidget())
+
+// Then call to finish TTFD when your long running work within your widget is done.
+
+SentryDisplayWidget.of(context).reportFullDisplay();
```
Comment (buenaflor) [inline CHANGELOG.md]: Does it have to be guarded with mounted?

File: flutter/lib/src/navigation/sentry_navigator_observer.dart [hunk 21]
```diff
@@ -262,22 +255,27 @@ class SentryNavigatorObserver extends RouteObserver<PageRoute<dynamic>> {
...
     }
 
     final transactionContext = SentryTransactionContext(
-      name,
+      routeName,
       SentrySpanOperations.uiLoad,
       transactionNameSource: SentryTransactionNameSource.component,
       origin: SentryTraceOrigins.autoNavigationRouteObserver,
     );
+    _timeToDisplayTracker?.transactionId = transactionContext.spanId;
```
Comment (buenaflor) [inline flutter/lib/src/navigation/sentry_navigator_observer.dart]: I'm not sure if this entirely fixes the problem, since the function is still running as async there's a chacne this will still be executed at some point later rather than before the widget is built

File: CHANGELOG.md (hunk 17 above)
Comment (buenaflor) [reply CHANGELOG.md]: we should also give an example on how to use it for stateless widgets

File: CHANGELOG.md (hunk 20 above)
Comment (denrase) [reply CHANGELOG.md]: I omitted it here to not bloat the sample and there is a warning if it's needed.

File: flutter/lib/src/navigation/sentry_navigator_observer.dart (hunk 21 above)
Comment (denrase) [reply flutter/lib/src/navigation/sentry_navigator_observer.dart]: The transaction context creation is sync, and the router didPush should always be called before the widget is build. So we'd have the reference in any case.

Only problem i'd see is if a user tries to immediatley call `reportFullDisplay` sync, as the transaction has not been started at this point. But then again, there's no point in using the API this way.

File: CHANGELOG.md (hunk 17 above)
Comment (buenaflor) [reply CHANGELOG.md]: as discussed it makes sense to have stateless widgets assume its TTFD is equal to TTID

File: flutter/lib/src/navigation/sentry_navigator_observer.dart (hunk 21 above)
Comment (buenaflor) [reply flutter/lib/src/navigation/sentry_navigator_observer.dart]: but the `_startTransaction` function is not sync, I assume there could be edge cases where the event loop won't pick up this function in time and then a timing issue might occur again

I'm thinking it's safer to move the transaction context creation and assignment out of this async function and pass the context in _startTransaction as a parameter

File: CHANGELOG.md (hunk 17 above)
Comment (buenaflor) [reply CHANGELOG.md]: that means then we should recommend using the SentryDisplayWidget generally

File: CHANGELOG.md [hunk 22]
```diff
@@ -1,5 +1,30 @@
...
+sentryDisplay?.reportFullyDisplayed()
+
+// Alternatively, you can wrap your widget in `SentryDisplayWidget`.
+
+SentryDisplayWidget(child: YourWidget())
+
+// Then call to finish TTFD when your long running work within your widget is done.
+
+SentryDisplayWidget.of(context).reportFullDisplay();
+```
```
Comment (buenaflor) [inline CHANGELOG.md]: last comment for this: let's recommend using the widget and have the manual api as an alternative

**Comment by buenaflor** [comment]
@denrase I've done some tests on Android and Web

✅  TTFD reported correctly when navigating to screen and reportFullyDisplayed() is called

✅ TTFD auto finishes after timeout (default 30s)

✅ TTFD in progress in Screen A, navigate to Screen B, then Screen A TTFD finishes async - should not finish TTFD of Screen B

✅ StatelessWidget auto-reporting - TTFD reported immediately for StatelessWidget and should be the same as TTID

✅ Multiple reportFullyDisplayed() calls - Only first call counts, subsequent calls ignored

✅ Late reportFullyDisplayed() call - Call after 30s timeout should be ignored

🚫 Navigate from Screen A to Screen B where Screen A does not do reportFullyDisplayed but Screen B does
    * Expected outcome: screen B has successful TTFD, Screen A should be deadline_exceeded
    * Actual outcome: screen B and A have deadline_exceeded on Android
    * For some reason on Web this works fine but not on Android
 
✅ TTFD disabled doesn’t track

**Comment by denrase** [comment]
@buenaflor Fixed, we called clear one too many times, and also after async calls. So with this race condition it would clear the transactionId right before we'd get the display reference.

**Comment by buenaflor** [comment]
Thx I'll have a look

**Comment by buenaflor** [comment]
looks good 👍 

@denrase can you check the changelog and see if everything is correct, I modified it a bit

**Comment by denrase** [comment]
@buenaflor LGTM 👍

**Review by buenaflor — APPROVED** [review]
failing tests are flaky (unrelated to this pr), looks good
