### PR TITLE
Ref: Add error and stacktrace parameter to logger

### LINKED ISSUE #462: Change method signature of the logger to match Dart's log method
The method signature of the Sentry Logger should match (or map closely) to the [Dart log method](https://api.dart.dev/stable/2.12.4/dart-developer/log.html).

### PR DESCRIPTION
**Pull request by ueman**
## :scroll: Description
Adds  error and stacktrace parameter to logger.
This is in order to get better bug reports and also to improve the output of our logs.

## :bulb: Motivation and Context
Closes #462

## :green_heart: How did you test it?
Existing test pass

## :pencil: Checklist

- [x] I reviewed submitted code
- [ ] I added tests to verify changes
- [x] I updated the docs if needed
- [x] All tests passing
- [ ] No breaking changes

### CODE REVIEW

File: dart/lib/src/enricher/io_enricher_event_processor.dart [hunk 1]
```diff
@@ -70,10 +70,12 @@ class IoEnricherEventProcessor extends EventProcessor {
         // This throws sometimes for some reason
         // https://github.com/flutter/flutter/issues/83921
         executable = Platform.executable;
-      } catch (exception) {
+      } catch (exception, stackTrace) {
         _options.logger(
           SentryLevel.info,
```
Comment (marandaneto) [inline dart/lib/src/enricher/io_enricher_event_processor.dart]: lets change to `error` then?

Comment (marandaneto) [reply dart/lib/src/enricher/io_enricher_event_processor.dart]: I meant instead of `SentryLevel.info`, it should be `SentryLevel.error`, so its not resolved uet

File: CHANGELOG.md [hunk 2]
```diff
@@ -5,6 +5,7 @@
 * Feat: Add Culture Context (#491)
 * Feat: Capture failed requests as event (#473)
 * Feat: `beforeSend` callback accepts async code (#494)
+* Ref: Add error and stacktrace parameter to logger (#503)
```
Comment (marandaneto) [inline CHANGELOG.md]: lets add the breaking change entry

**Review by marandaneto — APPROVED** [review]
LGTM
