### PR TITLE
Set `anrEnabled` enabled per default

### LINKED ISSUE #2864: Can we enable `anrEnabled` by default on Android
### Description

Based on our SDK, this is because historically, the stack trace typically hangs on the MessageChannel from Flutter; so when an ANR occurs in a Flutter app, the stack trace could potentially point to Flutter's MessageChannel implementation rather than the actual cause of an ANR.

Source: https://github.com/getsentry/sentry-dart/blob/08aff508096305d5e200243a441832821bc3164a/flutter/lib/src/sentry_flutter_options.dart#L69

Per [Flutter 3.29 Release Notes](https://medium.com/flutter/whats-new-in-flutter-3-29-f90c380c2317):
    
`Starting in 3.29, Flutter on Android and iOS execute Dart code on the application's main thread, and there is no longer a separate UI thread. This is the first part in a series of changes to improve platform interop on mobile platforms, as it allows making synchronous calls to and from the platform without the overhead of serialization and message passing.`

---

Let's find out if it makes sense to auto-enable it now

### PR DESCRIPTION
**Pull request by denrase**
## :scroll: Description

- Set `anrEnabled` enabled per default
- Update sample app to trigger ANR

## :bulb: Motivation and Context

Closes #2864

## :green_heart: How did you test it?

Tests & sample app triggering ANR.

## :pencil: Checklist

- [x] I reviewed submitted code
- [x] I added tests to verify changes
- [x] All tests passing
- [x] No breaking changes

### CODE REVIEW

File: flutter/lib/src/sentry_flutter_options.dart [hunk 1]
```diff
@@ -68,7 +68,7 @@ class SentryFlutterOptions extends SentryOptions {
   /// Disabled by default as the stack trace most of the time is hanging on
   /// the MessageChannel from Flutter, but you can enable it if you have
   /// Java/Kotlin code as well.
-  bool anrEnabled = false;
+  bool anrEnabled = true;
```
Comment (buenaflor) [inline flutter/lib/src/sentry_flutter_options.dart]: Pls update docs above

**Review by buenaflor — APPROVED** [review]
