### PR TITLE
Fix: Dio event processor safelly bails if no DioError in the exception list

### LINKED ISSUE #790: Catch StateError in sentry_dio
_Platform:_
- [X]  Dart
- [ ]  Flutter Android or iOS
- [ ]  Flutter Web

_IDE:_
- [X]  VSCode
- [ ]  IntelliJ/AS
- [ ]  XCode
- [ ]  Other, which one?

_split-debug-info and obfuscate (Flutter Android or iOS) or CanvasKit (Flutter Web):_
- [ ]  Enabled
- [X]  Disabled

_Platform installed with:_
- [X] pub.dev
- [ ] GitHub

Output of the command `flutter doctor -v` below:

[√] Flutter (Channel stable, 2.10.1, on Microsoft Windows [Version 10.0.22000.556], locale ru-RU)
    • Flutter version 2.10.1 at G:\Flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision db747aa133 (5 weeks ago), 2022-02-09 13:57:35 -0600
    • Engine revision ab46186b24
    • Dart version 2.16.1
    • DevTools version 2.9.2

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0-rc1)
    • Android SDK at G:\AndroidSdk
    • Platform android-31, build-tools 31.0.0-rc1
    • ANDROID_HOME = G:\AndroidSdk
    • ANDROID_SDK_ROOT = G:\AndroidSdk
    • Java binary at: G:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2021.1)
    • Android Studio at G:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[√] VS Code, 64-bit edition (version 1.65.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.36.0

[√] Connected device (4 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 12 (API 31) (emulator)
    • Windows (desktop)            • windows       • windows-x64    • Microsoft Windows [Version 10.0.22000.556]
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 99.0.4844.51
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 96.0.1054.62

[√] HTTP Host Availability
    • All required HTTP hosts are available

The version of the SDK (See pubspec.lock):
**6.4.0**

---
I have the following issue:

Sentry fll 

**Steps to reproduce:**

Init:
```
  await SentryFlutter.init(
    (options) {
      options
        ..dsn = 'someDSN'
        ..debug = true
        ..tracesSampleRate = 1.0;
    },
    appRunner: () => runApp(
     .....
    ),
  );
}
```
```
  dio.addSentry(
    maxRequestBodySize: MaxRequestBodySize.medium,
    captureFailedRequests: true, // <==== Enable
  );
```
```
final response = await dio.get<Map<String, Object?>>('/some_wrong_url'); // catch 404 status code
```

**Actual result:**
```
[sentry] [debug] Could not convert DioError to SentryException
.....
[sentry] StateError (Bad state: No element)
[sentry] #0      Iterable.first (dart:core/iterable.dart:624:7)
#1      DioEventProcessor._removeDioErrorStackTraceFromValue
package:sentry_dio/src/dio_event_processor.dart:78
#2      DioEventProcessor.apply
package:sentry_dio/src/dio_event_processor.dart:48
#3      SentryClient._processEvent
package:sentry/src/sentry_client.dart:289
           <asynchronous suspension>
#4      SentryClient.captureTransaction
package:sentry/src/sentry_client.dart:246
           <asynchronous suspension>
#5      Hub.captureTransaction
package:sentry/src/hub.dart:467
           <asynchronous suspension>
#6      SentryTracer.finish
package:sentry/src/sentry_tracer.dart:103
           <asynchronous suspension>
#7      new SentryTracer.<anonymous closure>
package:sentry/src/sentry_tracer.dart:50
           <asynchronous suspension>

```

**Expected result:**

There should be no `StateError`

### PR DESCRIPTION
**Pull request by marandaneto**
## :scroll: Description
Fix: Dio event processor safelly bails if no DioError in the exception list

## :bulb: Motivation and Context
Closes https://github.com/getsentry/sentry-dart/issues/790

## :pencil: Checklist

- [X] I reviewed submitted code
- [ ] I added tests to verify changes
- [ ] I updated the docs if needed
- [X] All tests passing
- [X] No breaking changes

### CODE REVIEW

File: dio/lib/src/dio_event_processor.dart [hunk 1]
```diff
@@ -9,6 +9,9 @@ import 'package:sentry/src/sentry_exception_factory.dart';
 /// It adds information about [DioError.response] if present and also about
 /// the inner exceptions.
 class DioEventProcessor implements EventProcessor {
+  // Because of obfuscation, we need to dynamically get the name
+  static final _dioErrorType = (DioError).toString();
```
Comment (ueman) [inline dio/lib/src/dio_event_processor.dart:13]: It's so weird that one can not do `DioError.toString()` directly.

File: dio/lib/src/dio_event_processor.dart [hunk 2]
```diff
@@ -73,9 +76,13 @@ class DioEventProcessor implements EventProcessor {
...
-    var dioSentryException = exceptions
-        .where((element) => element.type == dioError.runtimeType.toString())
-        .first;
+    final dioSentryExceptions =
+        exceptions.where((element) => element.type == _dioErrorType);
+
+    if (dioSentryExceptions.isEmpty) {
+      return exceptions;
+    }
+    var dioSentryException = dioSentryExceptions.first;
```
Comment (ueman) [inline dio/lib/src/dio_event_processor.dart:85]: This whole method is kinda ugly, but I also don't have a better idea. It also ignores the fact, that there is the theoretic possibility that there are two DioErrors. But once again, I also don't have a better idea :/

File: dio/lib/src/dio_event_processor.dart [hunk 3]
```diff
@@ -73,9 +76,13 @@ class DioEventProcessor implements EventProcessor {
...
     DioError dioError,
   ) {
-    var dioSentryException = exceptions
-        .where((element) => element.type == dioError.runtimeType.toString())
-        .first;
+    final dioSentryExceptions =
+        exceptions.where((element) => element.type == _dioErrorType);
+
+    if (dioSentryExceptions.isEmpty) {
+      return exceptions;
```
Comment (ueman) [inline dio/lib/src/dio_event_processor.dart:83]: Should this bailout be logged?

**Review by ueman — APPROVED** [review]
Looks good to me :shipit:

File: dio/lib/src/dio_event_processor.dart (hunk 3 above)
Comment (marandaneto) [reply dio/lib/src/dio_event_processor.dart:83]: Don't think so, there was nothing to be removed, The processor should keep going anyway with what's available.

File: dio/lib/src/dio_event_processor.dart (hunk 2 above)
Comment (marandaneto) [reply dio/lib/src/dio_event_processor.dart:85]: Yeah, I understand, don't have a better idea either, so I believe it's fine, constructing a brand new exception (with the information you have available) would be maybe a bit better code-wise but the result would be the same.

File: dio/lib/src/dio_event_processor.dart (hunk 1 above)
Comment (marandaneto) [reply dio/lib/src/dio_event_processor.dart:13]: Can't we? I just copied your version from the other PR :D

Comment (ueman) [reply dio/lib/src/dio_event_processor.dart:13]: Without the parenthesis, it's not valid code

**Review by brustolin — APPROVED** [review]
