### PR TITLE
Fix TTID timing issue

### LINKED ISSUE #2274: TTID and TTFD are not measured, due to timing issues
### Platform

Flutter Mobile

### Obfuscation

Disabled

### Debug Info

Enabled

### Doctor

[✓] Flutter (Channel stable, 3.24.1, on macOS 14.3 23D56 darwin-arm64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.1)
[✓] VS Code (version 1.92.2)
[✓] Connected device (4 available)            
[✓] Network resources

### Version

8.8.0

### Steps to Reproduce

Sometimes, due to timing issues, the transaction is not registered and consequently not sent to Sentry.

Videos, where repro captured:

Couple initial navigation events registered, but last one not. On screencast, you can see, that there is no message in console.
https://github.com/user-attachments/assets/e8b84e11-7ecb-4dea-8215-9130078469cf
https://github.com/user-attachments/assets/9888c394-f59e-4bf5-9e6f-1fc98d382e36

Minimal code, where I was able to reproduce the issue: https://github.com/givip/sentry_repro

This happens because sometimes method [completeTracking()](https://github.com/getsentry/sentry-dart/blob/3adbea907f8c71f0046e66eed0d4206d1d2a8043/flutter/lib/src/navigation/time_to_initial_display_tracker.dart#L122) was called earlier than [trackRegularRouteTTD()](https://github.com/getsentry/sentry-dart/blob/3adbea907f8c71f0046e66eed0d4206d1d2a8043/flutter/lib/src/navigation/time_to_display_tracker.dart#L33)

### Expected Result

All transactions should be registered

### Actual Result

Sometimes, the transaction is not registered and consequently not sent to Sentry.

### Are you willing to submit a PR?

No

### PR DESCRIPTION
**Pull request by denrase**
## :scroll: Description

- Await finish before starting new route
- Persist timestamp if completed was called before start because of async transaction start

## :bulb: Motivation and Context

The creation of the transaction takes longer than `SentryDisplayWidget` takes to finish init. This PR safes the completion timestamp internally of the ttid tracker and uses it when finishing. The start timestamp is always before, as it is created before the async transaction start.

Closes [#2274](https://github.com/getsentry/sentry-dart/issues/2274)

## :green_heart: How did you test it?

Unit tests

## :pencil: Checklist

- [x] I reviewed submitted code
- [x] I added tests to verify changes
- [ ] No new PII added or SDK only sends newly added PII if `sendDefaultPii` is enabled
- [ ] I updated the docs if needed
- [x] All tests passing
- [x] No breaking changes

### CODE REVIEW

**Comment by buenaflor** [comment]
nice, I think that might be the fix, looks right to me at least

File: flutter/lib/src/navigation/sentry_navigator_observer.dart [hunk 1]
```diff
@@ -159,8 +159,10 @@ class SentryNavigatorObserver extends RouteObserver<PageRoute<dynamic>> {
 
     // Clearing the display tracker here is safe since didPush happens before the Widget is built
     _timeToDisplayTracker?.clear();
-    _finishTimeToDisplayTracking();
-    _startTimeToDisplayTracking(route);
+
+    DateTime timestamp = _hub.options.clock();
+    _finishTimeToDisplayTracking(endTimestamp: timestamp);
+    _startTimeToDisplayTracking(route, timestamp);
```
Comment (buenaflor) [inline flutter/lib/src/navigation/sentry_navigator_observer.dart:165]: why don't we put them both in an async function with await? or does that modify the desired behaviour.

Comment (denrase) [reply flutter/lib/src/navigation/sentry_navigator_observer.dart:165]: The navigator tests were broken because of it. Also, this did not fix the problem, so it's ok to revert.

**Review by buenaflor — APPROVED** [review]
