### PR TITLE
Provide a way to cause an example native crash from Flutter

### LINKED ISSUE #219: Provide a way to cause an example native crash from Flutter
I am trying to migrate from the flutter_sentry package which has this option.
In hindsight I found myself using this often to test the correct integration.

It would be great if there was something like `SentryFlutter.nativeCrash()` which would use the method channel to create an example crash on the native side.

### PR DESCRIPTION
**Pull request by martinhaintz**
## :scroll: Description
add SentryFlutter.nativeCrash() using MethodChannels for Android and iOS

## :bulb: Motivation and Context
close #219 

## :green_heart: How did you test it?
Android Emulator and iOS Simulator. Also, I added a `SentryFlutter.nativeCrash` button to the example app.

## :pencil: Checklist

- [x] I reviewed submitted code
- [ ] I added tests to verify changes
- [x] No new PII added or SDK only sends newly added PII if `sendDefaultPii` is enabled
- [ ] I updated the docs if needed
- [x] All tests passing
- [x] No breaking changes

### CODE REVIEW

File: flutter/android/src/main/kotlin/io/sentry/flutter/SentryFlutterPlugin.kt [hunk 1]
```diff
@@ -466,4 +467,8 @@ class SentryFlutterPlugin : FlutterPlugin, MethodCallHandler, ActivityAware {
       )
     result.success(serializedScope)
   }
+
+  private fun crash(result: Result) {
+    error("This is a fatal error caused by SentryFlutter.nativeCrash.")
```
Comment (martinhaintz) [inline flutter/android/src/main/kotlin/io/sentry/flutter/SentryFlutterPlugin.kt]: @buenaflor @denrase can you please have a look at this implementation? Feel free to improve, as I am not a Kotlin expert.

Comment (martinhaintz) [reply flutter/android/src/main/kotlin/io/sentry/flutter/SentryFlutterPlugin.kt]: I improved the implementation. So this should be sufficient now.

File: flutter/lib/src/sentry_flutter.dart [hunk 2]
```diff
@@ -249,11 +249,7 @@ mixin SentryFlutter {
   /// Only for iOS and macOS.
   static Future<void> pauseAppHangTracking() {
     if (_native == null) {
-      // ignore: invalid_use_of_internal_member
-      Sentry.currentHub.options.logger(
-        SentryLevel.debug,
-        'Native integration is not available. Make sure SentryFlutter is initialized before accessing the pauseAppHangTracking API.',
-      );
+      _logNativeIntegrationNotAvailable("pauseAppHangTracking");
```
Comment (buenaflor) [inline flutter/lib/src/sentry_flutter.dart:252]: thx for cleaning up 🙏

File: flutter/lib/src/sentry_flutter.dart [hunk 3]
```diff
@@ -280,4 +272,20 @@ mixin SentryFlutter {
   static set native(SentryNativeBinding? value) => _native = value;
 
   static SentryNativeBinding? _native;
+
+  static Future<void> nativeCrash() {
```
Comment (buenaflor) [inline flutter/lib/src/sentry_flutter.dart:279]: pls add docs here that this its purpose is to trigger a native crash for debug purposes etc..

File: CHANGELOG.md [hunk 4]
```diff
@@ -4,6 +4,7 @@
 
 ### Features
 
+- Add `SentryFlutter.nativeCrash()` using MethodChannels for Android and iOS ([#2239](https://github.com/getsentry/sentry-dart/pull/2239))
```
Comment (buenaflor) [inline CHANGELOG.md:7]:
```suggestion
- Add `SentryFlutter.nativeCrash()` using MethodChannels for Android and iOS ([#2239](https://github.com/getsentry/sentry-dart/pull/2239))
  - This can be used to test if native crash reporting works  
```

or something similar, you can redefine the sentence if you want

File: flutter/lib/src/sentry_flutter.dart [hunk 5]
```diff
@@ -280,4 +272,23 @@ mixin SentryFlutter {
   static set native(SentryNativeBinding? value) => _native = value;
 
   static SentryNativeBinding? _native;
+
+  /// Use `nativeCrash()` to crash the native implementation and test/debug the crash reporting for native code.
+  /// This should not be used in production code.
+  /// Only for Android and iOS
```
Comment (denrase) [inline flutter/lib/src/sentry_flutter.dart]: and macOS

**Review by denrase — CHANGES_REQUESTED** [review]
Please also add a test to `sentry_native_channel_test.dart`

**Review by denrase — APPROVED** [review]
