### PR TITLE
fix(dart): Dont guard user behind `sendDefaultPii`

### LINKED ISSUE #3504: Dont guard all user info with `sendDefaultPii`
### Description

If a user manually sets User on the scope, we should send it with logs and metrics, regardless of sendDefaultPii

### PR DESCRIPTION
**Pull request by buenaflor**
## :scroll: Description

The user API is manual (not inferred) so that's why we do not need to gate it behind `sendDefaultPii`

This has recently been discovered to be a develop documentation issue and therefore a bug.

See https://develop.sentry.dev/sdk/telemetry/metrics/#user-attributes

## :bulb: Motivation and Context

Closes https://github.com/getsentry/sentry-dart/issues/3504

## :green_heart: How did you test it?
Unit tests, manual

## :pencil: Checklist

- [x] I reviewed submitted code
- [x] I added tests to verify changes
- [x] No new PII added or SDK only sends newly added PII if `sendDefaultPii` is enabled
- [ ] I updated the docs if needed
- [ ] All tests passing
- [x] No breaking changes

### CODE REVIEW

File: packages/dart/lib/src/constants.dart [hunk 1]
```diff
@@ -89,16 +89,16 @@ abstract class SemanticAttributesConstants {
...
+  /// Users are manually set on the scope, therefore this is not gated by `sendDefaultPii`.
   static const userId = 'user.id';
 
-  /// The user email (gated by `sendDefaultPii`).
+  /// The user email.
+  /// Users are manually set on the scope, therefore this is not gated by `sendDefaultPii`.
   static const userEmail = 'user.email';
 
-  /// The user IP address (gated by `sendDefaultPii`).
-  static const userIpAddress = 'user.ip_address';
```
Comment (buenaflor) [inline packages/dart/lib/src/constants.dart:99]: we dont use this currently so we can remove it

File: packages/flutter/example/lib/main.dart [hunk 2]
```diff
@@ -114,6 +114,15 @@ Future<void> setupSentry(
...
   );
+
+  Sentry.configureScope((scope) {
+    final user = SentryUser(
+      id: SentryId.newId().toString(),
+      name: 'J. Smith',
+      email: 'j.smith@example.com',
+    );
+    scope.setUser(user);
+  });
```
[the remark this answers is not in the document]
Comment (buenaflor) [reply packages/flutter/example/lib/main.dart:125]: that's fine we dont need to

File: packages/dart/lib/src/telemetry/default_attributes.dart [hunk 3]
```diff
@@ -23,21 +23,20 @@ Map<String, SentryAttribute> defaultAttributes(SentryOptions options,
...
-      }
-      if (user.name != null) {
-        attributes[SemanticAttributesConstants.userName] =
-            SentryAttribute.string(user.name!);
-      }
-      if (user.email != null) {
-        attributes[SemanticAttributesConstants.userEmail] =
-            SentryAttribute.string(user.email!);
-      }
+  // Users are manually set on the scope, therefore this is not gated by `sendDefaultPii`.
```
Comment (denrase) [inline packages/dart/lib/src/telemetry/default_attributes.dart]: We could also add this comment in the user setter on scope.

**Review by denrase — APPROVED** [review]
Looks good, just one suggestion.

File: packages/dart/lib/src/telemetry/default_attributes.dart (hunk 3 above)
Comment (buenaflor) [reply packages/dart/lib/src/telemetry/default_attributes.dart]: I think we can leave it commented in the default attributes and the constants file - in the future we will only us attributes so this is the source of truth anyway

the setUser API doesn't really know about these attributes
